### ISSUE TITLE
move  issues of docker-project to docker-library by ￥100

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#1]
1. show all the docker-project items
docker-activemq  ✔
docker-akeneo  ✔
docker-alfresco ✔
docker-algolia ✔
docker-ansible ✔
docker-apache ✔
docker-apex ✔
docker-apisix ✔
docker-awx ✔
docker-bigbluebutton✔
docker-bt✔
docker-budibase✔
docker-caddy✔
docker-canal✔
docker-cells✔
docker-ckan✔
docker-clamav✔
docker-cloudbeaver✔
docker-cmak✔
docker-codeserver✔
docker-collabora✔
docker-coredns✔
docker-couchdb✔
docker-countly✔
docker-dgraph✔
docker-directus✔
docker-discuz✔
docker-discuzq✔
docker-docusaurus✔
docker-dolibarr✔
docker-drupal✔
docker-elasticsearch✔
docker-elk✔
docker-erpnext✔
docker-espocrm✔
docker-falcon✔
docker-geoserver✔
docker-ghost✔
docker-gitlab✔
docker-gogs✔
docker-grafana✔
docker-graylog✔
docker-guacamole✔
docker-haproxy✔
docker-influxdb✔
docker-jenkins✔
docker-jetty✔
docker-jitsi✔
docker-joomla✔
docker-jumpserver✔
docker-jupyterhub✔
docker-kafka✔
docker-kibana✔
docker-knowage✔
docker-kodcloud✔
docker-kong✔
docker-library✔
docker-logstash✔
docker-magento✔
docker-mariadb✔
docker-matomo✔
docker-mattermost✔
docker-mautic✔
docker-mediawiki✔
docker-memadmin✔
docker-memcached✔
docker-metabase✔
docker-mingdao✔
docker-minio✔
docker-mongocompass✔
docker-mongodb✔
docker-mongoexpress✔
docker-moodle✔
docker-mysql✔
docker-neo4j✔
docker-netdata✔
docker-nextcloud✔
docker-nextterminal✔
docker-nginx✔
docker-nginxproxymanager✔
docker-nocodb✔
docker-nopcommerce✔
docker-odoo✔
docker-onlyoffice✔
docker-onlyofficedocs✔
docker-opencart✔
docker-opencv✔
docker-opensearch✔
docker-oracle✔
docker-owncloud✔
docker-pgadmin✔
docker-phpmyadmin✔
docker-pimcore✔
docker-portainer✔
docker-postgresql✔
docker-prestashop✔
docker-projector✔
docker-prometheus✔
docker-rabbitmq✔
docker-rainbond✔
docker-rancher✔
docker-redash✔
docker-redis✔
docker-redisinsight✔
docker-redmine✔
docker-rethinkdb✔
docker-rocketchat✔
docker-runtime✔
docker-sakai✔
docker-saleor✔
docker-scratch✔
docker-seafile✔
docker-sqlserver✔
docker-squid✔
docker-srs✔
docker-sscms✔
docker-strapi✔
docker-suitecrm✔
docker-superset✔
docker-template✔
docker-tensorflow✔
docker-theia✔
docker-tinyproxy✔
docker-tomcat✔
docker-traefik✔
docker-typesense✔
docker-typo3✔
docker-umbraco✔
docker-varnish✔
docker-vault✔
docker-visualstudio✔
docker-vtiger✔
docker-webmin✔
docker-wireguard✔
docker-wordpress✔
docker-xwiki✔
docker-zabbix✔
docker-zammad✔
docker-zentao✔

2. the kind of issue
all of the issue of docker-project: include open and closed

3. rename issue title endwith [appname]

**Comment by xyt52** [comment]
~
for(( i=0;i<${#name[*]};i++)) do {
    j=$[$i+1]
    echo "transfer and rename $j ${name[i]}"
    gh issue edit $j --title "${name[i]}    [issue 所在的 project]"
    gh issue transfer $j Websoft9/docker-library
}&
done;
~
