### ISSUE TITLE
Update version to [2.24.1] for [portainer] ￥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#1028]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by czj69233** [comment]
### docker logs portainer_re75d:
```
2024/12/09 07:03AM INF github.com/portainer/portainer/api/cmd/portainer/main.go:310 > encryption key file not present | filename=portainer
2024/12/09 07:03AM INF github.com/portainer/portainer/api/cmd/portainer/main.go:334 > proceeding without encryption key |
2024/12/09 07:03AM INF github.com/portainer/portainer/api/database/boltdb/db.go:124 > loading PortainerDB | filename=portainer.db
2024/12/09 07:03AM INF github.com/portainer/portainer/api/internal/ssl/ssl.go:80 > no cert files found, generating self signed SSL certificates |
2024/12/09 07:03AM INF github.com/portainer/portainer/api/chisel/service.go:228 > generated a new Chisel private key file | private-key=/data/chisel/private-key.pem
2024/12/09 07:03:12 server: Reverse tunnelling enabled
2024/12/09 07:03:12 server: Fingerprint iETd9h06ZxwrG4GK5dNSkVDbxE/6XKuMOea+7v63Idg=
2024/12/09 07:03:12 server: Listening on http://0.0.0.0:8000
2024/12/09 07:03AM INF github.com/portainer/portainer/api/cmd/portainer/main.go:601 > starting Portainer | build_number=131 go_version=go1.23.2 image_tag=2.24.1-linux-amd64 nodejs_version=18.20.5 version=2.24.1 webpack_version=5.88.2 yarn_version=1.22.22
2024/12/09 07:03AM INF github.com/portainer/portainer/api/http/server.go:349 > starting HTTP server | bind_address=:9000
2024/12/09 07:03AM INF github.com/portainer/portainer/api/http/server.go:365 > starting HTTPS server | bind_address=:9443
```
### screenshoot:
![image](https://github.com/user-attachments/assets/4469edd8-ce4a-468e-9418-edbafeb4512f)
![image](https://github.com/user-attachments/assets/68772b29-2db0-4a52-97e9-bcb883144cef)
![image](https://github.com/user-attachments/assets/0824c095-ed0a-4ea2-99a7-9ca15fab0cfe)
