### ISSUE TITLE
Update version to [v2.8.0] for [redpandaconsole] ￥10

### ISSUE THREAD

**Issue by qiuf12** [Websoft9/docker-library#1031]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by czj69233** [comment]
### docker logs redpandaconsole_sr51t:
```
{"level":"info","msg":"config filepath is not set, proceeding with options set from env variables and flags"}
{"level":"info","ts":"2024-12-09T05:59:11.877Z","msg":"started Redpanda Console","version":"v2.8.0","built_at":"1733243925"}
{"level":"info","ts":"2024-12-09T05:59:11.890Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
{"level":"info","ts":"2024-12-09T05:59:11.916Z","msg":"successfully connected to kafka cluster","advertised_broker_count":1,"topic_count":0,"controller_id":0,"kafka_version":"v3.8"}
{"level":"info","ts":"2024-12-09T05:59:13.241Z","msg":"Server listening on address","address":"[::]:8080","port":8080}
```
### screenshoot:
![image](https://github.com/user-attachments/assets/d7307c43-8aa1-4513-ad02-a3f6149d3d71)
![image](https://github.com/user-attachments/assets/cfe28c8c-0a0f-4123-b5ca-dab8a94f3a48)
