### ISSUE TITLE
Update version to [0.58.0] for [trivy] ￥10

### ISSUE THREAD

**Issue by qiuf12** [Websoft9/docker-library#1038]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by czj69233** [comment]
### docker logs trivy_yu6qb:
```
null
```
### screenshoot:
![image](https://github.com/user-attachments/assets/6af1c862-c6fb-4ed6-81a9-e778bef33bbe)
![image](https://github.com/user-attachments/assets/934be4f3-1f76-4838-810a-9afa386ca0e3)
