### ISSUE TITLE
Update version to [2.2.1] for [flowise] ￥10

### ISSUE THREAD

**Issue by qiuf12** [Websoft9/docker-library#1047]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by czj69233** [comment]
### docker logs flowise_ds6ps:
```
2024-12-09 08:59:02 [INFO]: Starting Flowise...
2024-12-09 08:59:03 [INFO]: 📦 [server]: Data Source is initializing...
2024-12-09 08:59:18 [INFO]: 📦 [server]: Data Source has been initialized!
2024-12-09 08:59:18 [INFO]: ⚡️ [server]: Flowise Server is listening at :3000
```
### screenshoot:
![image](https://github.com/user-attachments/assets/fbeb81e2-9cfd-4022-9be9-944ad4cabc68)
![image](https://github.com/user-attachments/assets/6bb2845c-5707-4599-8594-3b1a140c79c6)
![image](https://github.com/user-attachments/assets/a65e01b4-11b2-41e6-b0b3-ea674d7e900b)
