### ISSUE TITLE
Update version to [0.18] for [kopia]

### ISSUE THREAD

**Issue by qiuf12** [Websoft9/docker-library#1053]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [ ] Check the official installation docs of this application
- [ ] Add a comment with docker logs
- [ ] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [ ] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [ ] System testing for dev branch

**Comment by czj69233** [comment]
Cannot find kopia.
![image](https://github.com/user-attachments/assets/650e7463-912f-443f-866a-b52dbaf843cc)
