### ISSUE TITLE
Improve docker-compose for using latest template[akeneo]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#11]
refer to: https://github.com/Websoft9/docker-akeneo/blob/main/docker-compose.yml

Please accord with docker-compose standard

**Comment by viafcccy** [comment]
We can learn from it:
1. set default value, like: ${APP_ENV:-prod}
${varname:-word}，如果varname存在且非null，则返回其值；否则，返回word。用途：如果变量未定义，则返回默认值。
2. ...
