### ISSUE TITLE
Running is OK, but login failed[nextcloud]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#118]
Running is OK, but login failed
```
内部服务器错误
服务器不能完成您的请求。

如果再次发生这种情况，请将下面的技术详细信息发送给服务器管理员。

更多细节可以在服务器日志中找到。

技术细节
远程地址：222.240.12.89
请求 ID：p3PoISPW70zsMqMtdvSC
```

**Comment by QiuJiaHon** [comment]
Access through untrusted domain

![image](https://user-images.githubusercontent.com/95324527/147799056-3d4e85d5-ba23-4e23-acdf-643f53f9e99b.png)

**Comment by chendelin1982** [comment]
Transfer to: https://github.com/Websoft9/docker-nextcloud/issues/3
