### ISSUE TITLE
配置环境变量，支持 JSON Web Token (JWT) 安全访问[onlyofficedocs]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#128]
**What type of your feature request?**  

- [ ] Add new features

官方参考：[Configuring JWT for ONLYOFFICE Docs](https://helpcenter.onlyoffice.com/installation/docs-configure-jwt.aspx)

## 使用方法
1. 在 ONLYOFFICE Docs 配置 secret key
2. 在 Nextcloud 等 三方软件集成时，配置 secret key，实现安全访问

![image](https://user-images.githubusercontent.com/62225175/196082579-04c943c2-cad4-4e9e-9717-0cc707dbdb88.png)

**Comment by chendelin1982** [comment]
done
