### ISSUE TITLE
Opencart Products Page error [opencart]

### ISSUE THREAD

**Issue by LalicNine** [Websoft9/docker-library#134]
**Describe the bug**

After click the "product" button on main Page and it mention this error.
错误：在第49行的/var/www/html/system/library/image.php中调用未定义函数 Opencart\System\Library\imagecreatefromjpeg()

**Comment by chendelin1982** [comment]
It seem Opencart core error, have submit issue to Official repo: https://github.com/opencart/opencart/issues/11918

**Comment by chendelin1982** [comment]
should
![image](https://user-images.githubusercontent.com/16741975/200109141-5ea76e26-1726-41c6-ace2-ccb83f3e1c1c.png)


Now
![image](https://user-images.githubusercontent.com/16741975/200109131-47d92733-f549-4b06-8fbe-013503e743e7.png)

so, need configure jpeg for gd before: https://github.com/Websoft9/docker-library/blob/main/apps/runtime/src/Dockerfile.php

**Comment by chendelin1982** [comment]
```
RUN apt-get update && apt-get upgrade -y; \
    apt-get install -y wget unzip zip zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev libwebp-dev libzip-dev libc-client-dev imagemagick libkrb5-dev ghostscript ; \
    docker-php-ext-configure imap --with-kerberos --with-imap-ssl ; \
    docker-php-ext-configure gd --with-freetype --with-jpeg=/usr --with-webp ; \
    docker-php-ext-install -j "$(nproc)"  imap gd zip bcmath opcache exif mysqli ; \
    rm -rf /var/lib/apt/lists/* ; \
    mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
```

1. add libpng-dev libjpeg-dev
2. remove `--no-install-recommends` for apt install
