### ISSUE TITLE
Owncloud cannot trust this domain[owncloud]

### ISSUE THREAD

**Issue by LalicNine** [Websoft9/docker-library#137]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [x] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [x] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [x] Other (You should describe it) 

**Cloud PlatForm**

- [x] Azure
- [x] Aws
- [x] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs

```

### Bug Screenshot

![GN4JBY7BC{S3YEVS1PCQ%G0](https://user-images.githubusercontent.com/109707255/196919746-59d376d0-7cd8-4ab0-be08-e1d2ffe01ef8.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
-t 测试是OK的，生产后基于镜像测试无法进入

**Comment by chendelin1982** [comment]
Done

- OWNCLOUD_DOMAIN=${APP_URL}
- OWNCLOUD_TRUSTED_DOMAINS=${APP_URL}

以上两个环境变量都需要设置，且必须保持同样的值
