### ISSUE TITLE
PHP runtime dockerfile[runtime]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#162]
**What type of your feature request?**  

- [ ] Try only one dockerfile
- [ ] image verson try at compose.yml
- [ ] install php modules https://github.com/docker-library/drupal/blob/master/9.3/php8.0/apache-bullseye/Dockerfile
- [ ] install framework cli and create one app (.eg myrails)  https://github.com/Websoft9/docker-library/issues/155
- [ ] php module matrix https://github.com/mlocati/docker-php-extension-installer#supported-php-extensions

**Comment by qiaofeng1227** [comment]
php8.1-fpm
```
root@c50fc1a36a54:/var/www/html# php -m
[PHP Modules]
Core
ctype
curl
date
dom
fileinfo
filter
ftp
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zlib

[Zend Modules]

```

role_php
```
  - php-apcu
  - php-bcmath
  - php-bz2
  - php-cli
  - php-common
  - php-curl
  - php-fpm
  - php-gd
  - php-geoip
  - php-imagick
  - php-imap
  - php-intl
  - php-json
  - php-ldap
  - php-mbstring
  - php-mcrypt
  - php-memcache
  - php-mongodb
  - php-odbc
  - php-opcache
  - php-pdo
  - php-pear
  - php-pgsql
  - php-recode
  - php-redis
  - php-snmp
  - php-soap
  - php-tidy
  - php-xml
  - php-xmlrpc
  - php-zip
  - php-pecl-zip
  - php-gmp
```

**Comment by qiaofeng1227** [comment]
[build support vars](https://stackoverflow.com/questions/52429984/docker-compose-build-environment-variable)

**Comment by qiaofeng1227** [comment]
need add php module：
- mongodb (pecl ok)
- soap (ext ok)
-  xmlrpc (pecl Failed to download pecl/xmlrpc within preferred state "stable", latest release is version 1.0.0RC3, stability "beta", use "channel://pecl.php.net/xmlrpc-1.0.0RC3" to install)`pecl install xmlrpc-1.0.0RC3`
- apcu (有交互 -pecl) `echo "no" | pecl install  apcu`
- redis (有交互 -pecl)  `echo "no" | pecl install  redis`
- memcache (pecl) ` echo "no" | pecl install memcached`
- snmp (ext error: Could not find net-snmp-config binary. Please check your net-snmp installation）`apt-get install libsnmp-dev docker-php-ext-install -j "$(nproc)" snmp`
- tidy ( ext)
```
apt install libtidy-dev -y
docker-php-ext-install tidy
```
- mcrypt (pecl)(libmcrypt prefix? [autodetect] : ERROR: `/tmp/pear/temp/mcrypt/configure --with-php-config=/usr/local/bin/php-config --with-mcrypt' failed)
```
apt-get -y install libmcrypt-dev
echo "mcrypt" | pecl install mcrypt
```

- odbc (ext checking for Adabas support... cp: cannot stat '/usr/local/lib/odbclib.a': No such file or directory
configure: error: ODBC header file '/usr/local/incl/sqlext.h' not found!) [refer to](https://github.com/docker-library/php/issues/732)
```
RUN set -ex; \
        docker-php-source extract; \
        { \
                echo '# https://github.com/docker-library/php/issues/103#issuecomment-271413933'; \
                echo 'AC_DEFUN([PHP_ALWAYS_SHARED],[])dnl'; \
                echo; \
                cat /usr/src/php/ext/odbc/config.m4; \
        } > temp.m4; \
        mv temp.m4 /usr/src/php/ext/odbc/config.m4; \
        apt-get update; \
        apt-get install -y --no-install-recommends unixodbc-dev; \
        docker-php-ext-configure odbc --with-unixODBC=shared,/usr; \
        docker-php-ext-install odbc; \
        docker-php-source delete; \
        apt-get purge -y --auto-remove
```
- gmp (ext configure: error: GNU MP Library version 4.2 or greater required.)
```
apt-get install -y libgmp-dev
docker-php-ext-install gmp
```
- imagick (pecl  Please provide the prefix of ImageMagick installation [autodetect] :   ERROR: `/tmp/pear/temp/imagick/configure --with-php-config=/usr/local/bin/php-config --with-imagick=.' failed)

```
apt-get install libmagickwand-dev libmagickcore-dev -y
echo "imagick" | pecl install imagick
```
- imap (ext configure: error: utf8_mime2text() has new signature, but U8T_CANONICAL is missing. This should not happen. Check config.log for additional information.)
```
apt-get install -y --no-install-recommends libc-client-dev libkrb5-dev
docker-php-ext-configure imap --with-kerberos --with-imap-ssl 
docker-php-ext-install -j$(nproc) imap

```
- bz2 (ext checking for BZip2 in default path... not found configure: error: Please reinstall the BZip2 distributio)
```
apt-get install libbz2-dev -y
docker-php-ext-install -j$(nproc) bz2
```

暂时可以不安装
- geoip
- recode 
- pear

**Comment by qiaofeng1227** [comment]
>php7.4以上not support
- geoip
- recode

> not support
- pear
