### ISSUE TITLE
auto packaging [template]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#177]
**requirement: **  

install.sh -r redmine  --package

**solution design**  
1. docker,docker-compose bin  packages download from official website
2. Docker image package auto download by docker-compose-production.yml file
3. create requrement.txt (list)  for unzip
4. package application named appname-version
5. add install.sh for automatic installation and package it 
6. use init DB password for customer
7. install to /data/wwwroot/appname in customer's directory

**Comment by zengxc-1996** [comment]
use init password for customer: The declassification method is different
package application named appname-version:   Version fetching is done differently

**Comment by zengxc-1996** [comment]
need  to add the docker.service file

**Comment by zengxc-1996** [comment]
The file is too large to decompress. The tar must be unpacked

**Comment by zengxc-1996** [comment]
Submit to be tested

**Comment by zengxc-1996** [comment]
I only change the database containing 123456. I don't know how to determine whether it is a database or not .

![image](https://user-images.githubusercontent.com/63622990/115983488-ebf02b00-a5d3-11eb-9ce3-2470a62c7a2e.png)

**Comment by qiaofeng1227** [comment]
Done
