### ISSUE TITLE
add database configure before installation [typo3]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#194]
**What type of your feature request?**  

add database configure before installation, so that use not need to input the database connection.

**Comment by chendelin1982** [comment]
/var/lib/docker/volumes/docker-typo3_typo3conf/_data/LocalConfiguration.php

```
<?php
return [
    'BE' => [
        'explicitADmode' => 'explicitAllow',
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8',
                'driver' => 'mysqli',
                'host' => 'mysql',
                'user' => 'typo3',
                'password' => '892YcH1xDvaicQ'
            ],
        ],
    ],
```

If db connection is correct, the installation wizard will automaticlly to step3

**Comment by chendelin1982** [comment]
try solution:

1. cli: https://docs.typo3.org/p/helhum/typo3-console/main/en-us/Introduction/Index.html
2. https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Configuration/FactoryConfiguration.php
3. https://github.com/TYPO3-CMS/install (Functionality via CLI is also provided, e.g. the upgrade wizards or the installer can be executed on the command line.?)
4. https://github.com/crinis/typo3-docker/blob/master/10.4/Dockerfile

**Comment by chendelin1982** [comment]
Have pull request to https://github.com/martin-helmich/docker-typo3/pulls

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/190935116-2a6488a2-f453-4b4d-8729-ef4ab6a6b927.png)

**Comment by LalicNine** [comment]
file Loc:
/var/www/html/typo3_src-11.5.14/typo3/sysext/install/Classes/Controller/InstallerController.php

**Comment by LalicNine** [comment]
done
