### ISSUE TITLE
Document of typo3 needs to be confirmed[typo3]

### ISSUE THREAD

**Issue by LalicNine** [Websoft9/docker-library#195]
## Language

- [ ] Chinese
- [ ] English

## Content error

Provide us with documentation errors, e.g spelling mistake, wrong screenshot, code syntax error.

* URL: 
* Description: 
* Screenshot

## Content optimization

Provide us with content optimization, e.g easy to read, simplify the steps, step by step, precise expression.

* URL: 
* Description: 

## New content

Describe important content what do you think is important in this documentation.

**What content do you want to add?**  

(describe here) 

**Steps for the content**  

4. Modify file '....'

**Comment by qiaofeng1227** [comment]
新产品没上架
