### ISSUE TITLE
Improve docker-compose for using latest template #1[zabbix]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#205]

**Comment by zengxc-1996** [comment]
## Access via web page:
![image](https://user-images.githubusercontent.com/63622990/117756912-a1b4ae00-b251-11eb-92ab-1fca49aa75c1.png)

## Query authority:
![image](https://user-images.githubusercontent.com/63622990/117756941-a8dbbc00-b251-11eb-9b98-2a77e66a9dc9.png)

Resolved, the ZABBIX database name cannot be changed.

**Comment by zengxc-1996** [comment]
## zabbix 3.0 4.0 zabbix-snmtraps  status is restarting
![image](https://user-images.githubusercontent.com/63622990/117776897-a0de4500-b26e-11eb-8c59-62e5bd49cc8d.png)

## logs
![image](https://user-images.githubusercontent.com/63622990/117777068-d2571080-b26e-11eb-86e8-536c70dc3501.png)

**Comment by zengxc-1996** [comment]
## docker logs zabbix-mysql:
![image](https://user-images.githubusercontent.com/63622990/117802258-d9d6e380-b287-11eb-8d24-18e23c601e44.png)

add this line to docker-compose.yml :
  security_opt:
   - seccomp:unconfined
   
 Ignore Docker security validation

**Comment by zengxc-1996** [comment]
## docker logs zabbix-proxy and zabbix-server:
![image](https://user-images.githubusercontent.com/63622990/117802942-a34d9880-b288-11eb-8231-f0c06298afb7.png)

Not solved

**Comment by qiaofeng1227** [comment]
Done
