### ISSUE TITLE
镜像之间复制文件 for ￥50

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#217]
## 需求

1. 从jenkins镜像复制文件到jdk环境
```
COPY --from=jenkins/jenkins /usr/share/jenkins/jenkins.war /data/apps/jenkins/jenkins.war
```
2. 条件：仅 jdk17

## 方案
```
ARG BUILD_ENV=nojava17

RUN $BUILD_ENV=java17 when 发现当前环境是 17


FROM jenkins/jenkins as java17
ONBUILD COPY /usr/share/jenkins/jenkins.war /data/apps/jenkins/jenkins.war

FROM jenkins/jenkins as nojava17
ONBUILD RUN echo "I don't copy"

FROM build_${BUILD_ENV}
```

**Comment by zl-go** [comment]
将原Dockerfile.java中的内容修改为：
```
ARG JDK_VERSION=${JDK_VERSION}
FROM openjdk:${JDK_VERSION}-buster

ARG JDK_VERSION=${JDK_VERSION}
LABEL maintainer="help@websoft9.com"
LABEL version="${JDK_VERSION}"
LABEL description="JAVA runtime for ${JDK_VERSION}"
  
RUN apt update && apt install -y --no-install-recommends lsb-release  wget openssl git

RUN mkdir -p /data/apps/jenkins

ARG BUILD_ENV=nojava17

RUN if [ ${JDK_VERSION} = 17 ]; \
    then \
        BUILD_ENV=java17;\
        echo $BUILD_ENV;\
        echo "success!";\
    else  \
        echo $BUILD_ENV;\
        echo "do nothing"; \
    fi

FROM jenkins/jenkins as java17
ONBUILD COPY /usr/share/jenkins/jenkins.war /data/apps/jenkins/jenkins.war
ONBUILD RUN echo "copy success"

FROM jenkins/jenkins as nojava17
ONBUILD RUN echo "I don't copy"

FROM build_${BUILD_ENV}
# install supervisord
RUN apt install -y supervisor
```
运行指令:`docker build -f Dockerfile.java -t my_jdk . --build-arg JDK_VERSION=17`
执行结果为：
<img width="504" alt="4e0e1e25a71490bf99e8489e1fdb49b" src="https://user-images.githubusercontent.com/62973206/203886534-7946b8a5-27c8-4ff1-b3b2-ebfaf8f5ce38.png">

运行指令:`docker build -f Dockerfile.java -t my_jdk . --build-arg JDK_VERSION=8`
执行结果为：
<img width="489" alt="b7ef8cb35ea08cbff72de4a4dd821dd" src="https://user-images.githubusercontent.com/62973206/203886580-ddc2a533-a8d0-4e1a-900a-2c6210de6cf1.png">

并且`FROM build_${BUILD_ENV}`具有语法问题，导致后面的语句不可以执行。

结论：

1. 无论jdk版本是多少，拉取jenkins的动作一定会发生
2. ONBUILD后接的语句，无论jdk版本是多少都不会执行

> ONBUILD官方解释：
> The ONBUILD instruction adds to the image a trigger instruction to be executed at a later time, when the image is used as the base for another build.
