### ISSUE TITLE
Need create docker application for 【Canvas】

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#226]
1. create a canvas docker image by [official canvas install documentaion](https://github.com/instructure/canvas-lms/wiki/Production-Start)
2. SMTP ，refer to: https://github.com/Websoft9Archive/ansible-canvas/issues/3

**Comment by qiaofeng1227** [comment]
Requirements:

1. Generate an image based on the official canvas document
2. Dockerfile requires convenient support for subsequent upgrades, such as setting the node version, ruby version, and canvas release package path to environment variables
3. The initial login password for canvas needs to be randomized

**Comment by chendelin1982** [comment]
不再维护
