### ISSUE TITLE
graylog 找出通过命令输出版本的方法for ￥50

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#229]
graylog 找出通过命令输出版本的方法
1. 目前直接从镜像版本获取
2. 需要通过cli或者版本相关文件获取，精确到小数点后两位

**Comment by xyt52** [comment]
查看指令：
```
docker image inspect (docker image名称) | jq .[].Config.Labels
```
运行结果：
![AN13GEX2X8QL 07 ~J)H@E](https://user-images.githubusercontent.com/93903193/201845772-6f264b45-b504-43e8-964f-f676542af52d.png)
最后提取版本号指令：
```
docker image inspect graylog/graylog:4.3 | jq .[].Config.Labels | grep "org.label-schema.version" | cut -d ":" -f 2 | sed 's/\"//g'
```
