### ISSUE TITLE
redmine 找出通过命令输出版本的方法for ￥50 

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#230]
redmine 找出通过命令输出版本的方法

目前直接从镜像版本获取
需要通过cli或者版本相关文件获取，精确到小数点后两位

**Comment by xyt52** [comment]
查看指令
```
docker image inspect (docker image名称) | jq .[].ContainerConfig.Env
```
运行结果
![8L_N3~MWQ4NWYL@`T7S_ZWQ](https://user-images.githubusercontent.com/93903193/201856388-0387074a-4aef-4425-b4a6-14e76b2fd22b.png)
提取版本号指令：
```
docker image inspect redmine:4.2 | jq .[].ContainerConfig.Env | grep "REDMINE_VERSION" | cut -d "=" -f 2 | sed 's/\",//g'
```
