### ISSUE TITLE
Superset 设置多语言

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#233]
## Superset 设置多语言 ，如下图：

![image](https://user-images.githubusercontent.com/62225175/202384195-e08d9dec-84da-4c50-9958-2ab90f58c466.png)

![image](https://user-images.githubusercontent.com/62225175/202381188-546a75ee-fe6b-47fb-a3ca-f6ca36f7345f.png)

## 方法

[官方文档](https://superset.apache.org/docs/contributing/translations/#enabling-language-selection)

Enabling language selection
Add the LANGUAGES variable to your superset_config.py. Having more than one option inside will add a language selection dropdown to the UI on the right side of the navigation bar.

```
LANGUAGES = {
    'en': {'flag': 'us', 'name': 'English'},
    'fr': {'flag': 'fr', 'name': 'French'},
    'zh': {'flag': 'cn', 'name': 'Chinese'},
}
```

![image](https://user-images.githubusercontent.com/62225175/202382016-b95c4cbf-cc5c-44c5-bbe0-221fe9867c10.png)

**Comment by qiaofeng1227** [comment]
文档已经修改
