### ISSUE TITLE
【专题】 .env 文件中规范化环境变量前缀名称

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#236]
**What type of your feature request?**  

DB_ ES_ 开头的目前无法准确的表明它们是 Websoft9 规范化的环境变量，考虑加上 APP_ 前缀

一旦启动修改，首先需要考虑 Stackhub 是否兼容 APP_ 前缀的引入（即适用两种前缀）：

- [ ] 抽取密码
- [ ] ...

**Comment by qiaofeng1227** [comment]
任务分两个阶段：
1. 修改https://github.com/Websoft9/StackHub/blob/main/apps/roles/role_init，使其满足：
.env 含有DB_*_PASSWORD时，APP_DB_*_PASSWORD，都能把数据密码准确 过滤到/credentials/password.txt
2. 当1验证成功后，对应所有apps应用（.env 和docker-compose文件修改并测试）

**Comment by qiaofeng1227** [comment]
实施方案：

1. 使用 VSCode 进行精准替换（提前准备需要替换的字符串序列）  额外加一个无关的：https://github.com/Websoft9/intern_project/issues/159
2. 使用 VSCode 进行正则复查
3. 抽查（10个左右）

**Comment by chendelin1982** [comment]
Done
