### ISSUE TITLE
sqlserver client 使用- pay ¥50

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#237]
1. mcoud 运行sqlserver2019
2. 下载SSMS-Setup-CHS.exe 
3. 验证如果使用 SSMS-Setup-CHS 连接 sqlserver2019

**Comment by qiaofeng1227** [comment]
验证时候通知我，我要优化文档。

**Comment by Tooy1011** [comment]
经验证，能够使用windows本地的ssms，输入对应的服务器ip，用户名和密码连接到服务器上安装的sqlserver2019，并能正常使用。
