### ISSUE TITLE
【专题】服务器最小配置核对与整理 -

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#239]
1. 目前最小化配置在https://github.com/Websoft9Archive/ansible-appname等多个项目中
2. 在上面工程的[README.md](https://github.com/Websoft9Archive/ansible-XXX#readme)获取配置【内存和CPU】，更新到https://github.com/Websoft9/docker-library/blob/main/apps/appname/README-zh.md和README.md
3. 目前有如下apps需要对应，完成一个打一个勾
4. 建议使用脚本替换，并记录能够匹配的appname

 - [x] activemq
 - [x] akeneo
 - [x] alfresco
 - [x] ansible
 - [x] awx
 - [x] bt
 - [x] canvas
 - [x] cells
 - [x] cloudbeaver
 - [x] codeserver
 - [x] couchdb
 - [x] discuz
 - [x] discuzq
 - [x] dolibarr
 - [x] drupal
 - [x] elk
 - [x] erpnext
 - [x] espocrm
 - [ ] fastpanel
 - [x] ghost
 - [x] gitlab
 - [x] grafana
 - [x] graylog
 - [x] haproxy
 - [x] jenkins
 - [x] joomla
 - [x] kafka
 - [x] knowage
 - [x] kong
 - [x] magento
 - [x] mariadb
 - [x] matomo
 - [x] mattermost
 - [x] mediawiki
 - [x] memcached
 - [x] metabase
 - [x] mingdao
 - [x] mongocompass
 - [x] mongodb
 - [x] moodle
 - [x] mysql
 - [x] neo4j
 - [x] nextcloud
 - [x] odoo
 - [x] onlyoffice
 - [x] onlyofficedocs
 - [x] opencart
 - [x] oracle
 - [x] owncloud
 - [x] pgadmin
 - [x] phpmyadmin
 - [x] portainer
 - [x] postgresql
 - [x] prestashop
 - [x] rabbitmq
 - [x] redis
 - [x] redmine
 - [x] rethinkdb
 - [x] scratch
 - [x] seafile
 - [x] sqlserver
 - [x] srs
 - [x] suitecrm
 - [x] superset
 - [x] tensorflow
 - [x] vtiger
 - [x] webmin
 - [x] wordpress
 - [x] zabbix
 - [x] zentao

**Comment by chendelin1982** [comment]
不合适实习生处理。这个需要自己仔细的一个一个确认。

**Comment by qiaofeng1227** [comment]
对应完成
