### ISSUE TITLE
upgrade to v4.0 for [discuzq]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#242]
**What type of your feature request?**  

I have add [new dockerfile](https://github.com/Websoft9/docker-library/blob/main/apps/discuzq/Dockerfile-4.0-notest) for v4.0

1. It need test
2. php.ini

官方 composer 包目前无法下载：https://gitee.com/Discuz/Discuz-Q/issues/I63MHQ

**Comment by qiaofeng1227** [comment]
close
