### ISSUE TITLE
Output ERPNext version  - pay ¥50

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#248]
Output ERPNEXT version as format: v13.xx.22

**Comment by qiaofeng1227** [comment]
refer to: https://github.com/Websoft9/docker-library/blob/main/apps/erpnext/src/get_version.sh

**Comment by qiaofeng1227** [comment]
注意点：frappe版本可能和erpnext版本不一致

**Comment by xyt52** [comment]
代码
```
sudo echo "erpnext version:" $(docker exec -i erpnext cat /home/frappe/frappe-bench/apps/erpnext/erpnext/__init__.py|grep version |cut -d "=" -f2
) 1>> /data/logs/install_version.txt
```
运行结果：
![image](https://user-images.githubusercontent.com/93903193/206085690-c44c858e-d99c-4363-8277-cec9ff4b0619.png)
