### ISSUE TITLE
Login error  [superset] for ￥100

### ISSUE THREAD

**Issue by LalicNine** [Websoft9/docker-library#252]
**Describe the bug**

superset1.5.2登录后首页提示500错误。discovered by 童&徐

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context
```
superset1.5.2登录后首页提示500错误。
docker logs:
(Background on this error at: http://sqlalche.me/e/13/f405)
```
screenshot:
![JN5C{G%F3QFT(`Z%ZU5H7IY](https://user-images.githubusercontent.com/109707255/206944598-8ae28ec4-052e-421d-b944-844cd6575565.png)
![{NW@H%Z(O7Y3HKDX7{)CXBF](https://user-images.githubusercontent.com/109707255/206944604-844d1ccc-8b4f-49ee-84bc-194e55669f8b.png)

# bug error
(paste here) 

# service status 
(paste here) 

# error logs

```

### Bug Screenshot



## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
按照上游工程：
https://github.com/apache/superset/blob/master/docker-compose-non-dev.yml

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/208815069-5b238484-9b6d-414d-abc8-d157812e5e62.png)

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/208815713-f70df206-6426-4a59-a234-a330c362750a.png)
