### ISSUE TITLE
Azure Superset Docker Compose Issue

### ISSUE THREAD

**Issue by JohnDietrich-Pepper** [Websoft9/docker-library#258]
We are currently using your Azure Superset Image:
[Microsoft Azure Marketplace](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/vmlabinc1613642184700.superset?tab=overview&exp=ubp8)

We are trying to update Superset using the instructions here: 
[Upgrading Superset | Superset (apache.org)](https://superset.apache.org/docs/installation/upgrading-superset/#:~:text=Updating%20Superset%20Manually.%20To%20upgrade%20superset%20in%20a,and%20to%20backup%20your%20metadata%20database%20before%20upgrading.)

Upgrading Superset | Superset - The Apache Software Foundation
Upgrading Superset Docker Compose . First make sure to wind down the running containers in Docker Compose:
superset.apache.org

But when we run docker-compose down we are getting:
no configuration file provided: not found

if we try sudo docker-compose down we are getting
sudo: docker-compose: command not found

if we try docker-compose -f /data/apps/superset/docker-compose.yml down we get:
docker-compose -f /data/apps/superset/docker-compose.yml down
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.oneoff%3DFalse%22%3Atrue%2C%22com.docker.compose.project%3Dsuperset%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied

How do we update superset?

We would also like to configure alerts and e-mailed reports using:
[Alerts and Reports | Superset (apache.org) ](https://superset.apache.org/docs/installation/alerts-reports/)

How do we modify the existing docker file to add a headless browser.

**Comment by qiaofeng1227** [comment]
The past week was the statutory holiday of the Chinese New Year. I am very sorry for not responding for so long. We will investigate your question immediately and reply as soon as we have the result. Thank you for using our Superset products.
@JohnDietrich-Pepper

**Comment by JohnDietrich-Pepper** [comment]
Using "docker compose" instead of "docker-compose" seems to work.  However, it doesn't update Superset because it only updates to the latest version that you have on github 1.5.2 instead of 2.0.1 .

**Comment by JohnDietrich-Pepper** [comment]
Figured this out!  The new documentation is fantastic.
