### ISSUE TITLE
Superset not accessible 

### ISSUE THREAD

**Issue by JohnDietrich-Pepper** [Websoft9/docker-library#259]
To try and bypass the upgrade issue I cloned your superset git and changed the version to 2.0.1.  I installed on a fresh 22.04 VM and followed your instructions on the main page.  Docker and Superset installed just fine and is accessible on the localhost but is not accessible externally.

Azure has port 80 open and I verified that UFW is inactive.

**Comment by JohnDietrich-Pepper** [comment]
I figured out that Superset is being exposed on port 9001.  What I can't figure out is how the configuration I have and the configuration on the Azure instance you sell is different.  They both appear to be exposed on the same port internally and yet the Azure instance appears to be on port 80 (just type in the ip address).

**Comment by qiaofeng1227** [comment]
The past week was the statutory holiday of the Chinese New Year. I am very sorry for not responding for so long. We will investigate your question immediately and reply as soon as we have the result. Thank you for using our Superset products.
@JohnDietrich-Pepper

**Comment by qiaofeng1227** [comment]
1. websoft9's app is exposed on port 9001 by default, such as superser‘s [config file](https://github.com/Websoft9/docker-library/blob/main/apps/superset/.env)’:
```
APP_VERSION=1.5.2
APP_HTTP_PORT=9001
APP_NAME=superset
```

2. In order to allow users to access directly through ip or domain name, we installed nginx and forwarded port 127.0.0.1:9001 to 80, You can check whether nginx is installed by the following command：
```
sudo systemctl status nginx
```

nginx config file as following:
```
server {
    listen 80;
    server_name yourdomain.com;
    location / {
        proxy_pass  http://127.0.0.1:9001;
        proxy_redirect     off;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_max_temp_file_size 0;
        proxy_connect_timeout      90;
        proxy_send_timeout         90;
        proxy_read_timeout         90;
        proxy_buffer_size          4k;
        proxy_buffers              4 32k;
        proxy_busy_buffers_size    64k;
        proxy_temp_file_write_size 64k;
   }
   error_log /var/log/nginx/{{nginx_appname}}.yourdomain.com-error.log error;
   access_log  /var/log/nginx/{{nginx_appname}}.yourdomain.com-access.log;

   include extra/*.conf;
   
#------------- SSL Start --------------

#------------- SSL End  ---------------
}
```

**Comment by JohnDietrich-Pepper** [comment]
That is very helpful!
