### ISSUE TITLE
SuperSet Sending a Daily E-mail

### ISSUE THREAD

**Issue by JohnDietrich-Pepper** [Websoft9/docker-library#261]
Trying to get SuperSet to send a daily e-mail:

We are getting a "Failed taking a screenshot Message: 'geckodriver' executable needs to be in PATH."  

We have updated the SMTP settings per https://support.websoft9.com/en/docs/superset#smtp

We also noted that it said that docker compose worker needs to be set to dev per https://superset.apache.org/docs/installation/alerts-reports/

and tried that followed by docker compose up and it didn't work

**Comment by JohnDietrich-Pepper** [comment]
Changing the worker and beat to 2.0.1-dev in the docker-compose file and leaving the app at 2.0.1 worked.  Not a great solution though.

**Comment by qiaofeng1227** [comment]
thank you,If we find a solution in the normal release version, we will update the documentation and get back to you.
