### ISSUE TITLE
onlyoffice 容器一直重启

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#262]
![image](https://user-images.githubusercontent.com/43192516/215301666-e020e7b4-1e27-4c29-91e0-9db9c73ad799.png)

没有发现容器的错误日志

**Comment by qiaofeng1227** [comment]
1. 请参照[Onlyoffice的docker-compose文件](https://github.com/Websoft9/docker-library/blob/main/apps/onlyoffice/docker-compose.yml)

2. [onlyoffice官方](https://github.com/ONLYOFFICE/Docker-CommunityServer/blob/master/docker-compose.workspace.yml)是用mysql脚本创建了两个用户，我们产品只使用onlyoffice用户，不需要email用户。所以不使用脚本，通过 mysql的环境变量指定用户和密码。还有官方目前mysql升级到了8.0。是否问题出在这两个地方？


4. 通过改造1的compose文件，让onlyoffice能正常运行，通过9002和9003端口能正常访问画面

**Comment by qiaofeng1227** [comment]
[onlyoffice官方](https://github.com/ONLYOFFICE/Docker-CommunityServer/blob/master/docker-compose.workspace.yml)是用mysql脚本创建了两个用户，我们产品只使用onlyoffice用户，不需要email用户。所以不使用脚本，通过 mysql的环境变量指定用户和密码。是否问题出在这里？

**Comment by Tooy1011** [comment]
1. onlyoffice在centos7.9上能成功运行，显示界面；在ubuntu22.04上无法正常运行，界面无法显示
2. 在最开始的onlyoffice生产时，能够显示出界面，但测试时无法正常显示
