### ISSUE TITLE
【专题】websoft自定义镜像 dockerfile 依赖文件处理

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#263]
如果通过网络下载存在技术障碍的镜像必须文件，如何保存？

1. 建议保存在同项目的Dockerfile同级目录下面

Github对于50M以上的文件会报警，100M以上的文件限制上传，需要安装[插件](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github)

**Comment by chendelin1982** [comment]
use github artifact
