### ISSUE TITLE
鲲鹏服务器安装odoo - pay ¥100

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#265]
1. websoft9提供 鲲鹏服务器
2. 安装docker，docker-compose
3. 安装odoo

参照：[docker-library](https://github.com/Websoft9/docker-library#how-to-use-it)

**Comment by qiaofeng1227** [comment]
https://github.com/odoo/docker/blob/master/16.0/Dockerfile

**Comment by qiaofeng1227** [comment]
https://github.com/wkhtmltopdf/packaging

**Comment by Tooy1011** [comment]
arm版的wkhtmltopdf的下载地址[wkhtmltox_0.12.6-1.buster_arm64.deb](https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_arm64.deb)

总地址：[https://wkhtmltopdf.org/downloads.html](https://wkhtmltopdf.org/downloads.html)

![Image](https://user-images.githubusercontent.com/81067792/217735013-41fc68ac-3ec5-4bf9-b0e0-fda05c46476d.png)

脚本修改下载地址为：https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_arm64.deb
修改sh1值为：43d0db99ab0e6b5f60b465a49c764c50d6b31337

![Image](https://user-images.githubusercontent.com/81067792/217735531-5d97c188-e268-41b0-92be-3a028ced2a2f.png)
