### ISSUE TITLE
Gitlab 运行在2C4G服务器资源耗尽，卡顿且卡死 [Gitlab]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#268]
**Describe the bug**

Gitlab 运行在2C4G服务器资源耗尽，稍作操作（如新建项目，添加ISSUE）容易卡顿且卡死

![image](https://user-images.githubusercontent.com/62225175/218690588-69d469df-f972-4a3c-8956-19a350a211bc.png)

![image](https://user-images.githubusercontent.com/62225175/218690367-b7f993ea-09ec-41a1-b8e6-b49e240df077.png)

![image](https://user-images.githubusercontent.com/62225175/218692932-2bd68d61-3012-4f04-8153-238f67794cc1.png)

参考 ：[gitlab 502 bundle占用cpu100%问题（puma.pid权限问题）解决方案](https://zhuanlan.zhihu.com/p/482169399)

## Deployment method

- [x] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [x] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
需要2核心8g
