### ISSUE TITLE
Odoo 绑定域名后可以安装Website 但无法编辑，IP访问可以 [Odoo]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#269]
**Describe the bug**

问题描述：安装 Docker 版 [Odoo](https://github.com/Websoft9/docker-library/tree/main/apps/odoo)，并通过 Nginx proxy 模式配置域名。域名访问正常，但使用 Odoo Website 模块时，无法在域名的访问下编辑网站。  

可能存在的问题：Nginx 配置文件可能没有考虑 Odoo 某种[特殊](https://www.odoo.com/documentation/16.0/administration/install/deploy.html#id7)要求。

![image](https://user-images.githubusercontent.com/62225175/220003611-f00b7b2e-9edc-4650-9fbf-44ed90978d75.png)

![image](https://user-images.githubusercontent.com/62225175/220003727-8497dcbc-7dc5-48fd-a753-157896a89335.png)

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [x] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by zhaojing1987** [comment]
在App Store下安装和使用 ，并通过 Website 创建网站可以编辑和保存，未发现异常

**Comment by chendelin1982** [comment]
未发现异常. solved
