### ISSUE TITLE
Power Automate 数据挖缺场景for￥200  

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#270]
使用[Power Automate desktop](https://learn.microsoft.com/zh-cn/power-automate/desktop-flows/install) 从一个网页 A 中挖缺指定的数据，然后粘贴到另外一个网页 B 的表单中。

![image](https://user-images.githubusercontent.com/16741975/220034829-38603672-b286-4662-bbc8-293e75083b1c.png)

模拟场景：

1. 打开网页 A，双击网页某个位置（触发）后，所需的数据（预先定义）被拷贝
2. 打开网页 B，双击网页某个位置（触发）后，上一步骤的数据（预先定义）被粘贴到网页 B 中对应的表单中

![image](https://user-images.githubusercontent.com/16741975/220034692-62d72ae5-4e66-48cd-94a6-e28fb5188385.png)

**Comment by zl-go** [comment]
## 以登录，获取数据，填充数据的一个小例子作为power automate的入门教程

进入power automate之后，点击首页的【**新建流**】，输入名字，进入编辑页面。

使用左侧的【**浏览器自动化**】中的内容进行逻辑的编写，将其拖拽到中间即可。
![image](https://user-images.githubusercontent.com/62973206/220841951-ea27b6f0-82a5-43b1-9d89-ed40b5a22ef0.png)

### 一、打开页面
打开一个浏览器，有四种选择，任意选择一个即可，选取初始页面，涉及到挖取数据和填充数据两个页面，案例：挖取数据的页面http://webdriveruniversity.com/Data-Table/index.html

注意，我们每打开一个网页就生成一个对象，每个对象都有自己的名字，语法是 **% 名字 %** ，如果我们想在之后的逻辑中使用，也要用这个语法来引用。

这里我们不做改变，命名为**Browser**
![image](https://user-images.githubusercontent.com/62973206/220842339-9006a701-74d6-4373-b0d1-203c58af06d6.png)
打开完浏览器之后，就不用重新打开了，在刚才打开的浏览器中新建页面，进入需要填充数据的页面，这里我们模拟网页需要登录的场景https://www.saucedemo.com

我们将这个页面生成的对象命名为**NewBrowser**
![image](https://user-images.githubusercontent.com/62973206/220843155-1f0f4f6c-af5c-4881-8c46-0a1e3cbc55b4.png)

所以挖取数据的页面名叫Browser，填充数据的页面名叫NewBrowser

登录包括填写用户名，密码，然后点击登录按钮
![image](https://user-images.githubusercontent.com/62973206/220843801-b501e0b4-768b-47b2-855e-d463a0a6f7c3.png)

#### 二、填充数据
这里的示例网站用户名是standard_user，密码是secret_sauce

以填充用户名为例，web浏览器实例就是我们刚才打开的网页时所创建的对象
![image](https://user-images.githubusercontent.com/62973206/220844123-0f4398a6-52df-4bd5-b7f6-cc5dc25a2034.png)

这里我们操作的网页是NewBrowser，所以下拉选择
![image](https://user-images.githubusercontent.com/62973206/220846483-beeb82b6-092d-4c11-9577-c08842960a9f.png)

第二个是UI元素，就是告诉他我们要操作的页面上那个控件，我们点击【**添加UI元素**】
![image](https://user-images.githubusercontent.com/62973206/220847839-3dd4f411-5fce-495e-9909-93ea40dbb67c.png)

跳转到浏览器，注意要在我们登录页面上进行操作，
这里在用户名输入框的位置，ctrl+鼠标左键进行选择
![image](https://user-images.githubusercontent.com/62973206/220849569-a8b2b964-dfe1-40bb-bf83-a9b6a04a0d49.png)

选择UI元素完成之后，回到填写框，进行【文本】的输入，所以我们在输入框中填入用户名
![image](https://user-images.githubusercontent.com/62973206/220852971-bf0b871d-a105-444e-a3ae-694979bce628.png)

### 三、点击按钮
密码填写同理，最后进行按钮点击登录，在选择UI元素时，在网页中选择登录按钮
![image](https://user-images.githubusercontent.com/62973206/220853330-5948f01a-72ef-4177-abaa-b38322c9bec4.png)

模拟登陆后，进入下面所示页面，我们要点击右上角按钮进行需要填写的表单，按照上面图片进行按钮的点击
![image](https://user-images.githubusercontent.com/62973206/220853945-7cf4d173-1eab-4a05-bda7-33c28ae32ba7.png)

![image](https://user-images.githubusercontent.com/62973206/220853999-39aff2ab-4f9f-4aed-a30f-0081e651709a.png)

### 四、获取数据
现在进入数据获取阶段，不要点击保存，先返回我们获取数据的网页
![image](https://user-images.githubusercontent.com/62973206/220859794-fa015d43-e047-4e04-bf9e-48d62fea8ea2.png)

注意当我们选择数据的时候，软件会自动选择显示在浏览器中的页面，所以确保当前显示的页面是数据获取页面，我们右键选择数据，获取数据内容，注意，获取的数据会储存在变量中，命名时尽量直观，因为在后面填充数据的时候会使用变量名，我将获取的变量命名为FirstName

![image](https://user-images.githubusercontent.com/62973206/220855136-c51257e2-d333-4a48-8f25-fed52892bd28.png)

获取完我们想要的数据后，我们进行表单数据的填充，与登陆时不同的是，我们的文本不再输入常量，而是使用获取的数据，我们在前面将之命名为FirstName，所以根据语法，我们填入%FirstName%
![image](https://user-images.githubusercontent.com/62973206/220856867-439b7dc4-bbea-4afe-a1dd-934c6db780e4.png)

**Comment by chendelin1982** [comment]
请直接将子流的源码[拷贝并贴](https://learn.microsoft.com/zh-cn/power-automate/desktop-flows/how-to/share-export-desktop-flows)到下面。
