### ISSUE TITLE
Access to Web UI for teleport- pay ¥150

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#276]
#### What type of this issue?

- [x] research report

## Plan and do - Sub Tasks list

新增的项目[Teleport](https://github.com/Websoft9/docker-library/tree/main/apps/teleport)，我是参考[官方文档](https://goteleport.com/docs/try-out-teleport/docker-compose/) 改写的。

当前容器可以正常运行，但遇到两个问题：

- [ ] 如何访问 Web UI（当前访问被拒绝）？
- [ ] 如何创建管理员账号？

需调研这两个问题，并改进 docker-compose.yml （有必要的话）

**Comment by qiaofeng1227** [comment]
1. 访问url是https
2. step3 需要手动进入容器完成

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/222955946-41140e47-2295-4cc3-ad79-0aa87d90d92a.png)
