### ISSUE TITLE
Restart container will reset password   [bt]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#28]
**Describe the bug**

Restart container will reset password, this may cause the user's password reset

**Comment by chendelin1982** [comment]
solution for reference:

1.  https://github.com/Cyberbolt/baota/blob/main/app/script.py
2. https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/opt/bitnami/scripts/libwordpress.sh#L228
3. https://github.com/apache/activemq-artemis/blob/main/artemis-docker/docker-run.sh#L41

**Comment by chendelin1982** [comment]
```
    #判断是否是第一次初始化
    if not os.path.isfile('init.txt'):
        bt_init(data['port'], data['username'], data['password'])
        os.system('touch init.txt')
        print('设置成功\n')
```

init.txt 文件需存在于非 volume 目录，这样才可以保证仅创建容器时执行

**Comment by qiaofeng1227** [comment]
/www/server/panel/data/admin_path.pl  <=check this path
