### ISSUE TITLE
Canvas 问题集  [Canvas]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#281]
## 无法设置 / 获取 join code

你好，我在阿里云购买了贵公司的Canvas产品，并已经打开开放注册设置：【管理员】>【身份验证设置】>【提供者】开放教师和学生注册，然后我并无法在课程里面找到join code。根据网上教程，应该可以在课程设置里面打开并获取join code，但是我的设置里并无此项 （请查看附件），因此，目前我无法添加账号在Canvas里面。
此外，由于我们有比较多的学生，是否有可能我们直接帮助学生批量创建账号(如上传excel)，再将账号分配给学生？谢谢

官方文档：https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-enable-course-self-enrollment-with-a-join-code-or/ta-p/830

## 无法设置 / 查看课程分析 

官方文档：https://community.canvaslms.com/t5/%E6%8C%87%E5%8D%97%E4%B8%AD%E6%96%87%E7%89%88-%E8%AE%B2%E5%B8%88%E6%8C%87%E5%8D%97-instructor/%E6%88%91%E5%A6%82%E4%BD%95%E6%9F%A5%E7%9C%8B%E8%AF%BE%E7%A8%8B%E5%88%86%E6%9E%90/ta-p/440524

在我们的产品中，没有这些配置项。

**Comment by chendelin1982** [comment]
not maitance Canvas
