### ISSUE TITLE
DiscuzQ 3.0 升级到 4.1.2 方案(React版本) [DiscuzQ ]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#282]
[方案](https://discuzq.cc/index.php?s=quan&c=son&id=44)

升级版：3.0.6 和 4.0.0 和 4.0.1 和 4.0.2 版本 升级到 4.1.2-20230115 版本

第一步：进入容器，执行命令 php disco migrate 检查是否有报错，报错的情况下不要升级

第二步：[下载](https://drive.weixin.qq.com/s?k=AJoATQf2ABAcoVdeSM#/)升级文件包，覆盖到服务器文件

第三步：执行命令：php disco migrate  

第四步：执行命令：php disco db:seed --class=SettingsTableSeeder

**Comment by qiaofeng1227** [comment]
close
