### ISSUE TITLE
SMTP/pgAdmin中两步验证方案实现 for pgAdmin

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/docker-library#285]
**What type of your feature request?**  

![image](https://user-images.githubusercontent.com/54173243/231728345-eca69d10-7ff7-4726-a841-b082827f0342.png)
  
![image](https://user-images.githubusercontent.com/54173243/231728411-3dea9a63-83d7-45cd-af7f-0100ef5be64a.png)

**Is your feature request related to a problem? Please describe.**  
AWS中国上架前测试，提出这个问题，未能解决，请支持

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by chendelin1982** [comment]
SMTP 成功设置后邮件发送不成功，已向官方提交 [Issue](https://github.com/pgadmin-org/pgadmin4/issues/6134)
