### ISSUE TITLE
Incorrect Login Password [superset]

### ISSUE THREAD

**Issue by JesusEkie** [Websoft9/docker-library#286]
**Describe the bug**

After the deployment of the Docker image for superset we are unable to log into the system with the default password.
PS: The username and password have not been changed.

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [*] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [*] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

v2.0.1

**OS**

- [ ] Ubuntu18.x
- [*] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [*] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

## Bug reproduce

1. Run the command 'curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh && sudo systemctl start docker'
2. Run the command 'git clone https://github.com/Websoft9/docker-library'
3. Run the command 'cd docker-library && ls apps'
4. Run the command 'cd apps/superset
5. Run the command 'sudo docker network create websoft9 &&  sudo docker compose up -d'
3. open the URL/IP on the browser and try login with the default app credentials 'admin / uQ8E1wVTzG8SOk3!'
5. See error: Invalid Login

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
After another test, we should log in normally under the 2-core 8g server.
Would like to ask about your server configuration size？
