### ISSUE TITLE
app json中的版本同步到contenful 

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#287]
Update contentful action for the reason that version change to editon like below:

```
  "edition": [
    {
      "dist": "community",
      "version": ["latest", "207"]
    },
    {
      "dist": "enterprise",
      "version": ["latest", "207"]
    }
  ],
```

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/232353215-529a91bf-05c0-422d-9762-0293be80b382.png)

**Comment by chendelin1982** [comment]
Have complete syns all applications, need optimze:

- set option for all apps or changes apps
- syn change apps implementation
