### ISSUE TITLE
ONLYOFFICE DOCS EE 集成与开发[ONLYOFFICE DOCS ]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#288]
1、需要性能测试报告 √
2、文档不能编辑；参考：https://www.onlyoffice.com/office-for-nextcloud.aspx
3、文档的版本管理；参考：http://support.websoft9.com/docs/onlyofficedocs#%E5%A4%9A%E7%89%88%E6%9C%AC
4、ONLYOFFICE DOCS的 Debug 日志查看；已向原厂技术发工单：
5、ONLYOFFICE DOCS fonts 加载失败。参考：http://support.websoft9.com/docs/onlyofficedocs#addfonts

**Comment by chendelin1982** [comment]
closed, 已归档
