### ISSUE TITLE
容器启动后，APP_URL未写入服务器IP [Mattermost]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#289]
**Describe the bug**

容器启动后，APP_URL未写入服务器IP

APP_REPO=mattermost/mattermost-team-edition
APP_VERSION=latest
APP_HTTP_PORT=9001
APP_NAME=mattermost
APP_URL_REPLACE=true
**APP_URL=:9001**
APP_NETWORK=websoft9

手动修改后，程序正常运行。

## Deployment method

- [x] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [x] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
无法重现
