### ISSUE TITLE
output version on install_version.txt     [budibase]   ￥50

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#29]

**Comment by Tooy1011** [comment]
运行结果如下：
![Image](https://user-images.githubusercontent.com/81067792/203258393-92409476-b90a-4e51-b408-fe844829cd73.png)

**Comment by Tooy1011** [comment]
找到在 /app/package.json 和 /app/dist/package.json 两个文件中都写明了budibase web server的版本号


![Image](https://user-images.githubusercontent.com/81067792/203888385-f7e06df3-e2b8-491f-b0bd-f3817aebf9e1.png)

**Comment by Tooy1011** [comment]
echo "budibase version:"$(docker exec -i budibase grep "version" package.json|head -n 1|awk -F ":" '{print $2}')>> /data/logs/install_version.txt
