### ISSUE TITLE
Try use redis, Error: connect ECONNREFUSED 127.0.0.1:6379 [directus]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#306]
**Describe the bug**

When enable Redis connection, directus can not start and error below

```
[10:04:16.348] WARN: [lock-cache] Error: connect ECONNREFUSED 127.0.0.1:6379
    err: {
      "type": "Error",
      "message": "connect ECONNREFUSED 127.0.0.1:6379",
      "stack":
          Error: connect ECONNREFUSED 127.0.0.1:6379
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
      "errno": -111,
      "code": "ECONNREFUSED",
      "syscall": "connect",
      "address": "127.0.0.1",
      "port": 6379
    }

```

**Comment by craigharman** [comment]
@chendelin1982 I've experienced a similar issue, but first would need to confirm a few things.

- Are you using the docker container?
- Is Redis running?
- Are the Redis credentials correct?
- Do you redis credentials match what is stated above (ie. 127.0.0.1 and port 6379)?

**Comment by chendelin1982** [comment]
> @chendelin1982 I've experienced a similar issue, but first would need to confirm a few things.
> 
> * Are you using the docker container?
> * Is Redis running?
> * Are the Redis credentials correct?
> * Do you redis credentials match what is stated above (ie. 127.0.0.1 and port 6379)?

Hello, we are use Diectus docker image, you can see it [here](https://github.com/Websoft9/docker-library/tree/main/apps/directus)
If you have test redis with docker, you can submit us your PR. thanks

**Comment by qiaofeng1227** [comment]
add redis container
