### ISSUE TITLE
Always restart for starting [prestashop]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#328]
**Describe the bug**

初始化过程中，可能会失败。（不一定会出现）

```
$ doceker logs prestashop
* Checking if prestashop-db is available...

* DB server prestashop-db is available, let's continue !

* Shop seems setup but remaining install lock still present...

* Checking if prestashop-db is available...

* DB server prestashop-db is available, let's continue !

* Shop seems setup but remaining install lock still present...

* Checking if prestashop-db is available...

* DB server prestashop-db is available, let's continue !

* Shop seems setup but remaining install lock still present...

* Checking if prestashop-db is available...

* DB server prestashop-db is available, let's continue !

* Shop seems setup but remaining install lock still present...



$ docker logs prestashop-db

2023-08-04T04:19:34.144758Z 7 [Note] InnoDB: Stopping purge
2023-08-04T04:19:34.148345Z 7 [Note] InnoDB: Resuming purge
2023-08-04T04:19:34.152399Z 7 [Note] InnoDB: Stopping purge
2023-08-04T04:19:34.155845Z 7 [Note] InnoDB: Resuming purge
2023-08-04T04:19:34.283914Z 7 [Note] InnoDB: Stopping purge
2023-08-04T04:19:34.287617Z 7 [Note] InnoDB: Resuming purge

```

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [x] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [x] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [x] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by chendelin1982** [comment]
- prestashop cmd.sh: https://github.com/PrestaShop/docker/blob/master/base/config_files/docker_run.sh
- mysql innodb-purge: https://mysql.net.cn/doc/refman/8.0/en/innodb-purge-configuration.html
 
问题初步判断：Prestashop 安装导入数据到 MySQL 时，会对数据库产生一定的压力，从而触发 MySQL 一定的行为或 MySQL 与Linux系统占资源。

**Comment by qiaofeng1227** [comment]
It will present on low configuration server?

**Comment by chendelin1982** [comment]
8.0 not have this issue
