### ISSUE TITLE
complete docker compose  for [Cloudreve]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#336]
**What type of your feature request?**  

- [ ] docs: https://docs.cloudreve.org/getting-started/install#docker

**Comment by chendelin1982** [comment]
- [ ] temp_data? (声明volume指定自定义路径)

- [x] RPC 服务器地址 => http://aria2:6800
![image](https://github.com/Websoft9/docker-library/assets/43192516/beb38f9a-4116-4e8c-86d6-725d381a9b4d)

- [x] 离线下载服务?
  Cloudreve通过RPC方式驱动aria2进行离线下载

- [ ] cloudreve environment refer?

- [x] cloudreve.db?
  SQLite 数据库文件路径  https://docs.cloudreve.org/getting-started/config
- [ ] 777？
 Aria2执行下载命令的系统用户为p3terx，需要将/data/aria2目录给该用户赋权
  亦可使用命令 chown -R p3terx. /data/aria2 赋权

 user: root -> can not download

**Comment by qiaofeng1227** [comment]
单独docker 创建 volumes，cloudreve容器和aria2单独存在时声明volumes：download的用户都是root。和两容器同时存在时是一样的

**Comment by chendelin1982** [comment]
- [ ] compose up deleted database of Cloudreve ?  named volumes mount 
- [ ] aria2 secret not accept @ ?  
- [ ] 离线下载
  下载文件夹权限？
- [ ] folder: /data or /downloads  ?  two container use the same volume and path

**Comment by chendelin1982** [comment]
- create name volumes cloudreve-config, touch config.ini, touch cloudreve.db
- mount:  /var/lib/docker/volumes/cloudreve_r5j86_cloudreve-config/_data/

**Comment by zhilinxinyu** [comment]
> * create name volumes cloudreve-config, touch config.ini, touch cloudreve.db
> 
>     * mount:  /var/lib/docker/volumes/cloudreve_r5j86_cloudreve-config/_data/

  目前在容器中执行docker命令的测试未成功
