### ISSUE TITLE
complete docker compose for [Apache Airflow]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#340]
**What type of your feature request?**  

- [x] Add new features
- [ ] Improve current features

**Do you have Clear solution**  

- [x] No solution, need research
- [x] Yes, solution detail below

Discribe you solution here:  

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by zhaojing1987** [comment]
官方文档：[Running Airflow in Docker](https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html)

airflow-init 容器用于进行初始化，会进行资源检测，要求：
内存：至少4G
CPU核心：至少2个
磁盘空间：至少10G

为了安装时的权限，需要在.env 中设置AIRFLOW_UID，在linux下：
```
AIRFLOW_UID=0   # root用户
```
或者使用 ：echo -e "AIRFLOW_UID=$(id -u)" > .env
tips：这里在测试的时候没有设置这个环境变量，容器一直处于健康检查状态

结合官方的docker compose ，经过测试可以安装和启动成功，只要进行Websoft9的docker-library改造即可

**Comment by zhaojing1987** [comment]
$W9_ID-init  容器用于进行初始化，会进行资源检测和其他初始化工作，当其状态为：exited - code 0  时，表示正常，其他情况需要进入正常查看错误。

已完成docker compose的websoft9改造，可以安排进行测试
