### ISSUE TITLE
Operation not permitted [Collabora]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#346]
**Describe the bug**

```
In docker log sh: 1: /usr/bin/loolmount: Operation not permitted
```

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [x] Other (You should describe it)   

## System Environment

**Application Version**

latest

**CPU**

- [x] amd64, x86 
- [ ] arm64
- [ ] Other (You should describe it)

**Comment by chendelin1982** [comment]
I have fix it, please test it

**Comment by qiaofeng1227** [comment]
- [x] docker log   when nextcloud connection it and working, sometimes error
- [x] detail version
- [x] config file and environment variables
