### ISSUE TITLE
Improve docker-compose for using latest template   [codeserver]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#35]
1. project save problem
2. plugin install and uninstall
3. container  privilege

**Comment by zengxc-1996** [comment]
"end_check_versions.stdout_lines": [
        "mysql  Ver 14.14 Distrib 5.7.34, for Linux (x86_64) using  EditLine wrapper",
        "MongoDB shell version v4.0.24",
        "Docker version 20.10.6, build 370c289",
        "adminmongo version: \"version\": \"0.0.23\",",
        "phpmyadmin version: \"version\": \"5.1.0\",",
        "codeserver version: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005",
        "nginx version: nginx/1.20.0",
        "System version: CentOS 7.9",
        "Image name: codeserverzengxc-CentOS7.9"

**Comment by zengxc-1996** [comment]
tested OK !
