### ISSUE TITLE
不能设置语言 [Magento]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#360]
**Describe the bug**

## 设置前台

![image](https://github.com/Websoft9/docker-library/assets/62225175/3d64e3dc-feab-4a8e-aa24-0ebc6743bce1)

## 设置后台

![image](https://github.com/Websoft9/docker-library/assets/62225175/46d02b0f-4f13-4ca3-94cb-19cfa550ed08)

**Comment by laozhou0731** [comment]
对比2.4.3，语言目录 /var/lib/docker/volumes/magento_magento_data/_data/vendor/magento/language-zh_hans_cn 缺少文件 zh_Hans_CN.csv 

上传该文件，执行如下命令，能解决后台设置中文的问题：
![image](https://github.com/Websoft9/docker-library/assets/62225175/b132f553-b59d-46bd-9615-39f02756011f)

```
## 下载语言包
cd /var/lib/docker/volumes/magento_magento_data/_data/vendor/magento/language-zh_hans_cn 
wget -N https://raw.githubusercontent.com/magento-l10n/language-zh_CN/master/zh_CN.csv
## 进入容器，安装语言
docker exec -it magento bash
cd /bitnami/magento/
bin/magento setup:static-content:deploy zh_Hans_CN
bin/magento indexer:reindex
bin/magento cache:clean
bin/magento cache:flush
```

**Comment by laozhou0731** [comment]
[zh_Hans_CN.csv](https://github.com/Websoft9/docker-library/files/12326899/zh_Hans_CN.csv)


[zh_Hans_CN2.csv](https://github.com/mageplaza/magento-2-chinese-language-pack)

**Comment by qiaofeng1227** [comment]
Docker image env:  MAGENTO_MODE: Magento mode. Valid values: default, production, developer. Default: default  

refer to:  

* https://community.magento.com/t5/Magento-2-x-Technical-Issues/How-to-Create-Multi-Language-Store-in-Magento-2/td-p/256838
* https://hub.docker.com/r/bitnami/magento

develop can show language list, but can't tranlate the menu and other contents

**Comment by chendelin1982** [comment]
Resource for reference:

* [Magento official translations project](https://crowdin.com/project/magento-2)
* Magento supports two types of language packages: [Translation dictionaries and Language packages](https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/localization.html?mt=false)

**Comment by zhaojing1987** [comment]
When installing Magento, the official default is to only install the US version and not install other language packs. The other language packs need to be installed by oneself。How to Install Chinese Language Pack：

1. Get Language Pack：Magento officially released a translation of Chinese language writing on [ Crowdin Magento 2 Project](https://crowdin.com/project/magento-2/zh-CN), but the version and translation progress are incomplete 。For this reason，some third-party authors create some zh_CN language package based on translations provided at Crowdin Magento 2 Project。Such as：      
    - [mageplaza/magento-2-chinese-language-pack](https://github.com/mageplaza/magento-2-chinese-language-pack)：Updated 4 years ago
    - [magento-l10n/language-zh_CN](https://github.com/magento-l10n/language-zh_CN) ：Updated 2 months ago

    However，any third-party zh_CN language  package may miss some translations. We can use third-party language packs or create our own language packs based on crowdin。
    The third-party language pack as a complete CSV file can be directly downloaded and used. If you need to create your own language pack based on crowdin,。we need to merge the translations of all modules separately before using it.

2. Import Language Pack：
    A complete language pack that includes the following content:
     - Required license files
     - composer.json
     - registration.php that registers the language package
     - language.xml meta-information file
     - A translated CSV file
    During the installation of magento, the Chinese language pack was automatically installed, but the translation files were missing。The directory is located at: 
     `/var/lib/docker/volumes/magento_magento_data/_data/vendor/magento/language-zh_hans_cn && wget -N https://raw.githubusercontent.com/magento-l10n/language-zh_CN/master/zh_CN.csv`

     Like this: ![Image](https://github.com/Websoft9/docker-library/assets/7624828/d0350350-112c-4a0a-89a3-85c3bb9fc49d)
     We need to upload the CSV translation file obtained in the previous step to this directory。We need to upload the CSV translation file obtained in the previous step to this directory and rename it to: zh_Hans_CN.csv。Because the official command for the Chinese language pack is: zh_Hans_CN
    Entering the interior of the magento main container：`docker exec -it magento bash`
    Execute the following command：
    ```
    magento setup:static-content:deploy zh_Hans_CN    (Deploy static content for specified language and region to Magento 2)
    magento indexer:reindex    (Force rebuild of all indexes)
    magento cache:clean    (Clear Cache)
    magento cache:flush    (Flush  Cache )
    ```
3. switch language：
   From Magento 2 admin panel, navigate to admin(Your Account)> Account Setting (Your Account) >Interface Locale
Enter Account Setting
![Image](https://github.com/Websoft9/docker-library/assets/7624828/37bdde95-a441-4fa8-afec-4900fcf97249)
Choose Chinese：
![Image](https://github.com/Websoft9/docker-library/assets/7624828/c7b55a25-26fb-4c19-ac2d-f7f53f32e58b)
Save Account ，You will see the Chinese page：

![Image](https://github.com/Websoft9/docker-library/assets/7624828/20fbb208-7f05-4b3e-8b02-d4df189766e8)
