### ISSUE TITLE
spawn failed for [jupyterhub]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#361]
**What type of your feature request?**  

I don't know how to get the username and password of admin after running

**Comment by qiaofeng1227** [comment]
```
docker exec -it jupyterhub bash
adduser
```

login success, spawn failed:

![image](https://github.com/Websoft9/docker-library/assets/43192516/dbb750d3-18ee-4609-90f1-416c428961ec)


refer to: https://hub.docker.com/r/jupyterhub/jupyterhub#docker
