### ISSUE TITLE
Refused to load the script '<URL>' because it violates the following... for [discourse]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#362]
**Describe the bug**

Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> 'sha256-HZxBMVZe6P3MvHDZlFai9cUmLH+qwX6BNT3qTwNPATg='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

![image](https://github.com/Websoft9/docker-library/assets/16741975/e1b0ccc1-ccd3-4d91-8d08-0984d0e1c9ab)

**Comment by qiaofeng1227** [comment]
```
curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/discourse/docker-compose.yml > docker-compose.yml
docker-compose up -d
```

**Comment by qiaofeng1227** [comment]
![image](https://github.com/Websoft9/docker-library/assets/43192516/0cc3cb2b-f1a6-4662-8699-93e714463066)

**Comment by qiaofeng1227** [comment]
It is occured by websoft9's rule ?
