### ISSUE TITLE
Can'not export data and connect marketplace for [Akeneo]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#364]
**Describe the bug**

## Bug source

- [ ] Bugs from installation 
- [x] Bugs from first use
- [ ] Other (You should describe it)   

**不能导出数据**
![bf0551c7-f8b8-427b-b2a7-97967e5db559](https://github.com/Websoft9/docker-library/assets/62225175/0bdb544e-5f6e-4391-9bd9-2fa56821bbd2)

**不能连接到 appStore**
![image](https://github.com/Websoft9/docker-library/assets/62225175/c22b65b7-a1a5-49b1-9091-90be53cb675a)

通过权限修改，可以点击 connect ，但连接的地址是localhost:8080 
![dea6588e-eaff-4fd6-8144-fb2c5f223456](https://github.com/Websoft9/docker-library/assets/62225175/fe1eccd1-3742-4ad0-bdcd-5b1156289851)

![image](https://github.com/Websoft9/docker-library/assets/62225175/91c48adc-ae80-4fe0-a5b3-7e5ea0dfd4d8)

**Comment by chendelin1982** [comment]
This issue can be proccess after #301

**Comment by laozhou0731** [comment]
## Successfully connected to the marketplace (app strore)
### Authorize users to manage apps
First, follow the steps above to authorize the user (role) (Manager apps / Open apps)
### Configure the URL
Modify the /data/apps/akeneo/data/akeneo/.env.local file to change the AKENEO_PIM_URL to the server IP or DNS, for example AKENEO_PIM_URL=http://100.100.100.100

**Comment by chendelin1982** [comment]
We no longer maintain this image
