### ISSUE TITLE
升级至7.0 [Akeneo]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#365]
**What type of your feature request?**  

- [ ] Add new features
- [ ] Improve current features

**Do you have Clear solution**  

- [ ] No solution, need research
- [ ] Yes, solution detail below

Discribe you solution here:  

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by qiaofeng1227** [comment]
refer to : #301
