### ISSUE TITLE
没有添加php配置文件 [DiscuzQ]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#369]
**Describe the bug**

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**CPU**

- [ ] amd64, x86 
- [ ] arm64
- [ ] Other (You should describe it)   

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
there is conf.d on discuzq container:
/etc/php/7.2/fpm/conf.d

refer to: https://github.com/Websoft9/docker-library/blob/main/docs/code_owner.md#php-configuration


-----------------------
how to  add configuration to conf.d ?

------------------------test result--------
access discuzq container, edit php.ini for php-configuration, restart is OK.

**Comment by laozhou0731** [comment]
![image](https://github.com/Websoft9/docker-library/assets/62225175/fed03c26-333a-402a-b274-f1e0acc6858f)
