### ISSUE TITLE
重大更新 [DiscuzQ]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#371]
**What type of your feature request?**  

- 现有版本 首页加载太慢
- **已发布新版本 https://gitee.com/Discuz/discuzq**
- 添加php配置文件
https://github.com/Websoft9/docker-library/issues/369

**Comment by chendelin1982** [comment]
腾讯云官方已经停止维护 discuzq 镜像，截止 2023-12-18，discuzq 镜像已经 22个月没有更新
