### ISSUE TITLE
汉化 [Portainer]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#374]
**What type of your feature request?**  

## 汉化 Portainer
![image](https://github.com/Websoft9/docker-library/assets/62225175/6d49a7e8-7859-4735-badd-ec6516437a58)

### 方式二：使用[汉化包](http://code.imnks.com/zip/portainer-ce-public-cn-20221227.zip)，挂载 public 目录，将汉化包上传至该目录 。 [参考](https://github.com/portainer/portainer/blob/develop/build/linux/Dockerfile)

**Do you have Clear solution**  

- [ ] No solution, need research
- [ ] Yes, solution detail below

Discribe you solution here:  

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by chendelin1982** [comment]
Portainer CEO say it have not i18n project: https://github.com/orgs/portainer/discussions/9336
