### ISSUE TITLE
挂载安装目录，便于用户二开 [Odoo]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#376]
**What type of your feature request?**  

挂载安装目录，便于用户二开

**Do you have Clear solution**  

- [ ] No solution, need research
- [ ] Yes, solution detail below

Discribe you solution here:  

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by qiaofeng1227** [comment]
有个通用问题，在不删除挂载的情况下，如果把源码挂载出来，无法升级。

**Comment by qiaofeng1227** [comment]
源码所在路径：/usr/lib/python3/dist-packages/odoo

**Comment by chendelin1982** [comment]
You can see below code at Dockerfile, that mean /mnt/extra-addons is for developer
```
# Set permissions and Mount /var/lib/odoo to allow restoring filestore and /mnt/extra-addons for users addons
RUN chown odoo /etc/odoo/odoo.conf \
    && mkdir -p /mnt/extra-addons \
    && chown -R odoo /mnt/extra-addons
VOLUME ["/var/lib/odoo", "/mnt/extra-addons"]
```

**Comment by laozhou0731** [comment]
We should consider targeting developers, as there are actually users who need to do secondary development.
