### ISSUE TITLE
password.txt 内容改进 [PostgreSQL]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#377]
**Describe the bug**

![image](https://github.com/Websoft9/docker-library/assets/62225175/4c40d8a4-0f2b-4194-83ae-50dd874db02f)

- 缺少 db_host
- 用户名和数据库名与文档规范不符
## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [x] Other (You should describe it)   正常使用

## System Environment

**Application Version**

e.g v4.5

**CPU**

- [x] amd64, x86 
- [ ] arm64
- [ ] Other (You should describe it)   

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
已经修正
