### ISSUE TITLE
improve all apps refer to new template

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#380]
## 完成docker-compose.yml的改造, 流程：

1. 准备虚拟机或者云服务器
2. git clone https://github.com/Websoft9/docker-library.git
3. [改造docker-compose.yml以及.env文件，改造内容参照
4. 测试修改的app是否能正常运行
- 所有容器日志是否正常
- 如果是web应用，画面是否打开，能够通过.env文件的用户名和密码正常登陆
- 如果是DB或者MQ，需要测连接是否正常
5. 提交pull_request
6. websoft9 审核（如审核不通过，回到3再次改造）

### docker-compose.yml [【模板】](https://github.com/Websoft9/docker-library/blob/main/template/docker-compose.yml)

- W9_HTTP_PORT->W9_HTTP_PORT_SET(如果有其他外网端口也尾部加上_SET)
- Web应用的数据库外部端口全部删除
- 主容器名$W9_NAME变成$W9_ID,其他$W9_NAME环境变量都得变成$W9_ID
- 主数据库容器名由id和数据库类型决定：如$W9_ID-mysql,$W9_ID-mariadb,$W9_ID-mongodb
- 主容器的镜像地址需要用$W9_REPO替换
- 所有的容器都要追加 .env 声明
```
  wordpress:
    ports:
      - $W9_HTTP_PORT_SET:80
    env_file: .env

  mariadb:
    image: mariadb:10.4
    container_name: $W9_ID-mariadb
    env_file: .env

```

### .env [【模板】](https://github.com/Websoft9/docker-library/blob/main/template/.env)
- 所有带_SET结尾的变量是容器的外网端口
- web应用必须定义W9_HTTP_PORT_SET
- 如果主容器还有多个外网端口，如SSH端口，API端口，都需要定义成变量，如W9_SSH_PORT
- 单独数据库做应用时，W9_DB_PORT_SET就是数据库对外端口
- 【可修改item】放在最前面, 其中W9_REPO是主镜像的地址
```
W9_REPO=docker.io/bitnami/magento
W9_DIST=community
W9_VERSION=latest

POWER_PASSWORD=EGProfkuyL3ogd
```

- 【不可修改item】需要使用下列注释括起来
```
#### --  Not allowed to edit below environments when recreate app based on existing data  -- ####
W9_HTTP_PORT_SET=9001
W9_HTTP_PORT=80
W9_URL=Internet_IP:$W9_HTTP_PORT_SET
W9_DB_EXPOSE="mysql"
#### -------------------------------------------------------------------------------------------------- ####

```
- 非W9开头的容器自身的环境变量放在.env文件的最后
- 当是web应用时，需要定义W9_HTTP_PORT，它对应主应用的内部端口
- 删除W9_DB_*_PORT 和 W9_MQ_*_PORT 

### variables.json [【模板】](https://github.com/Websoft9/docker-library/blob/main/template/variables.json)

- version -> edition(contentful sync need to edit), 一般情况下只有社区版（community），版本号参照.env里面的版本
```
  "edition": [
    {
      "dist": "community",
      "version": [
        "3.7",
        "latest"
      ]
    }
  ]
```

**Comment by chendelin1982** [comment]
- [x] activemq
- [x] akaunting
- [x] akeneo
- [x] alfresco
- [x] ansible
- [x] apache
- [x] apex
- [x] apitable
- [x] appflowy
- [x] appsmith
- [x] arangodb
- [x] awx
- [x] budibase
- [x] caddy
- [x] chat2db
- [x] chatgptnextweb
- [x] clamav
- [x] cloudbeaver
- [x] codeserver
- [x] couchdb
- [x] dgraph
- [x] directus
- [x] discourse
- [x] discuz
- [x] discuzq
- [x] dolibarr
- [x] drupal
- [x] elastic
- [x] elasticsearch
- [x] erpnext
- [x] espocrm
- [x] excalidraw
- [x] focalboard
- [x] ghost
- [x] gitea
- [x] gitlab
- [x] gogs
- [x] grafana
- [x] graylog
- [x] haproxy
- [x] homeassistant
- [x] huginn
- [x] humhub
- [x] influxdb
- [x] jenkins
- [x] joomla
- [x] jupyterhub
- [x] kafka
- [x] kasmweb
- [x] knowage
- [x] kodbox
- [x] kong
- [x] magento
- [x] mariadb
- [x] matomo
- [x] mattermost
- [x] mautic
- [x] mediawiki
- [x] memcached
- [x] metabase
- [x] minio
- [x] mongocompass
- [x] mongodb
- [x] moodle
- [x] mysql
- [x] n8n
- [x] neo4j
- [x] netdata
- [x] nextcloud
- [x] nextterminal
- [x] nocobase
- [x] nocodb
- [x] nopcommerce
- [x] odoo
- [x] onlyoffice
- [x] onlyofficedocs
- [x] opencart
- [x] opensearch
- [x] oracle
- [x] owncloud
- [x] pgadmin
- [x] phpmyadmin
- [x] plausible
- [x] postgresql
- [x] prestashop
- [x] pydio
- [x] rabbitmq
- [x] redis
- [x] redisinsight
- [x] redmine
- [x] redpandaconsole
- [x] rethinkdb
- [x] rocketchat
- [x] scratch
- [x] seafile
- [x] sqlserver
- [x] srs
- [x] sscms
- [x] strapi
- [x] suitecrm
- [x] superset
- [x] teleport
- [x] tensorflow
- [x] theia
- [x] thingsboard
- [x] traefik
- [x] typesense
- [x] typo3
- [x] umami
- [x] vault
- [x] vtiger
- [x] webmin
- [x] wordpress
- [x] zabbix
- [x] zammad
- [x] zentao

**Comment by qiaofeng1227** [comment]
- [ ] activemq
- [ ] akaunting
- [ ] akeneo
- [ ] alfresco
- [ ] ansible
- [ ] apache
- [ ] apex
- [ ] apitable
- [ ] appflowy
- [ ] appsmith
- [ ] arangodb
- [ ] awx
- [ ] budibase
- [ ] caddy
- [ ] chat2db
- [ ] chatgptnextweb
- [ ] clamav
- [ ] cloudbeaver
- [ ] codeserver
- [ ] couchdb
- [ ] dgraph
- [ ] directus
- [ ] discourse
- [ ] discuz
- [ ] discuzq
- [ ] dolibarr
- [ ] drupal
- [ ] elastic
- [ ] elasticsearch
- [ ] erpnext
- [ ] espocrm
- [ ] excalidraw
- [ ] focalboard
- [ ] ghost
- [ ] gitea
- [ ] gitlab
- [ ] gogs
- [ ] grafana
- [ ] graylog
- [ ] haproxy
- [ ] homeassistant
- [ ] huginn
- [ ] humhub
- [ ] influxdb
- [ ] jenkins
- [ ] joomla
- [ ] jupyterhub
- [ ] kafka
- [ ] kasm-workspaces
- [ ] knowage
- [ ] kodbox
- [ ] kong
- [ ] magento
- [ ] mariadb
- [ ] matomo
- [ ] mattermost
- [ ] mautic
- [ ] mediawiki
- [ ] memcached
- [ ] metabase
- [ ] minio
- [ ] mongocompass
- [ ] mongodb
- [ ] moodle
- [ ] mysql
- [ ] n8n
- [ ] neo4j
- [ ] netdata
- [ ] nextcloud
- [ ] nextterminal
- [ ] nocobase
- [ ] nocodb
- [ ] nopcommerce
- [ ] odoo
- [ ] onlyoffice
- [ ] onlyofficedocs
- [ ] opencart
- [ ] opensearch
- [ ] oracle
- [ ] owncloud
- [ ] pgadmin
- [ ] phpmyadmin
- [ ] plausible
- [ ] postgresql
- [ ] prestashop
- [ ] pydio
- [ ] rabbitmq
- [ ] redis
- [ ] redisinsight
- [ ] redmine
- [ ] redpandaconsole
- [ ] rethinkdb
- [ ] rocketchat
- [ ] scratch
- [ ] seafile
- [ ] sqlserver
- [ ] srs
- [ ] sscms
- [ ] strapi
- [ ] suitecrm
- [ ] superset
- [ ] teleport
- [ ] tensorflow
- [ ] theia
- [ ] thingsboard
- [ ] traefik
- [ ] typesense
- [ ] typo3
- [ ] umami
- [ ] vault
- [ ] vtiger
- [ ] webmin
- [ ] wordpress
- [ ] zabbix
- [ ] zammad
- [ ] zentao
