### ISSUE TITLE
Mapping container port 1883  for MQTT [RabbitMQ]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#382]
1883/15675  is used for the MQTT 
MQTT is provided by MQTT Plugin. 

## Enable plugins: 
```
rabbitmq-plugins enable rabbitmq_mqtt
rabbitmq-plugins enable rabbitmq_web_mqtt   
```

## Client [MQTTX](https://github.com/emqx/MQTTX) 
**Connect RabbitMQ**
![image](https://github.com/Websoft9/docker-library/assets/62225175/5df7e029-1407-4fd0-98d5-021ee105bbf1)
**Add Exchanges in RabbitMQ**
![image](https://github.com/Websoft9/docker-library/assets/62225175/2f6c1eff-ad41-4e90-938a-3e9c2cb42a6b)
**Set Topic**
![image](https://github.com/Websoft9/docker-library/assets/62225175/81da8496-7018-4148-bbed-c72ae99bde36)

**Comment by laozhou0731** [comment]
![image](https://github.com/Websoft9/docker-library/assets/62225175/fa020f75-fa35-43d3-abfd-d09cb50a31ba)
1883

**Comment by chendelin1982** [comment]
solved

- [x] add docs
- [x] add application mqttx
- [x] improve RabbitMQ library
