### ISSUE TITLE
 The container status is abnormal for [ERPNext]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#407]
**Describe the bug**
After ERPNext is started normally, the erpnext-create-site container should be in the Exited state, but it remains in the Restarting state

![image](https://github.com/Websoft9/docker-library/assets/62225175/42398f2a-ea50-456b-8212-d96ba61261f6)

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [x] Other (**During use**)   

## System Environment

**Application Version**

e.g v4.5

**CPU**

- [ ] amd64, x86 
- [ ] arm64
- [ ] Other (You should describe it)   

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by zhilinxinyu** [comment]
Remove the parameter 'restart' from docker-compose.yml, while excution failed, throw exception code 1 and exit.

**Comment by chendelin1982** [comment]
refer to #516
