### ISSUE TITLE
magento store can not set chinese or other language

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#409]
![image](https://github.com/Websoft9/docker-library/assets/43192516/38bcf919-9a12-49d1-9468-f05ebf310de8)

can not select locale menu.

**Comment by chendelin1982** [comment]
refer to:

- https://github.com/magento/magento2/issues/10377
- https://magento.stackexchange.com/questions/217385/cannot-change-locale-language-magento-2

I seem have three possible method:

- cli 【√】
```
# scope-code is your store name
php bin/magento config:set --scope=stores --scope-code=default general/locale/code zh_Hans_CN
php bin/magento cache:clean
php bin/magento cache:flush
```
- change to dev mode -> set at console -> change to pro  【×】it will destroy container
- modify at html page develop mode：You can actually just delete the **"Disabled" and "readonly"** attribute in the dom  【√】

**Comment by qiaofeng1227** [comment]
you can change store language by cli or your browser console , please update documentation.
