### ISSUE TITLE
Check Discuzq initial when modify DB connections    [discuzq]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#42]
**What type of your feature request?**  

Check Discuzq initial when modify DB connections

**Comment by chendelin1982** [comment]
/config/config.php  will created after inti

**Comment by qiaofeng1227** [comment]
/tmp/cmd.sh是否会自动删除？如果会，则镜像需要重新生成

**Comment by chendelin1982** [comment]
If exsit /config/config.php, should modify the DB connection by this file
