### ISSUE TITLE
Wordpress Site URL Hardcode Internal_IP for [Wordpress]

### ISSUE THREAD

**Issue by cerebrux** [Websoft9/docker-library#436]
**Describe the bug**

The latest change 40a7880727fc91b4efbd20844c8ed18e35d4027c probably creates a hardcoded "Internal_IP" In Admin panel of wordpress under Site URL.

As a result I am not able to login using my domain name e.g. https://example.com/login. It redirects to 

`https://internet_ip/wp-login.php` 
## Bug source

- [ ] Bugs from first use

## System Environment
VPS Ubuntu 22.04 in a lxc container

**Application Version**

latest docker compose from your 

## Bug reproduce

1. git clone the repository
2. edit the .env with your desired settings e.g. changing passwords etc.
3. docker network create wordpress
4. docker compose up -d
5. go to the domain name that you have created A record for the server you run the docker container and complete the wordpress installation (Name, username, password, email etc.)

Once complete login. If successful check in the admin panel the General Settings --> Site URL --> has "https://Internal_URL" string

## Check Logs

`docker compose logs` shows that `wordpress-cli`  runs before the actual wordpress installation is complete. 

<img width="507" alt="Screenshot 2023-11-30 125420" src="https://github.com/Websoft9/docker-library/assets/914656/45600a4a-3594-4f14-8eb2-e4a54b15c47b">

Once Wordpress is complete it changes the homeurl and siteurl

<img width="753" alt="Screenshot 2023-11-30 125728" src="https://github.com/Websoft9/docker-library/assets/914656/7e33792c-1644-4508-bc45-ca0127418ca8">

### Bug Screenshot

If I open a new browser and go to https://example.com/login it redirects `https://internet_ip/wp-login.php` 

<img width="850" alt="Screenshot 2023-11-30 130030" src="https://github.com/Websoft9/docker-library/assets/914656/884ccad9-cfb9-4a53-a66c-db4bc9ae7733">

**Comment by cerebrux** [comment]
Workaround : 

1. Edit .env
2. Replce URL=Internal_IP with your actual FQND domain name e.g. URL=example.com
3. Now after the container is up you will be able to login

**Comment by chendelin1982** [comment]
hello, thanks for your suggestion. We have fix it:
1. W9_URL default is ""
2. Add below to wp-cli command
   ```
      if [ -z \"$W9_URL\" ]; then
        echo 'W9_URL is empty, not need to change, exiting...'
        exit 0
      fi
   ```

That mean if you don't  modify W9_URL, it have have hardcoded
