### ISSUE TITLE
The end check version of compnent "DiscuzQ" is not the real version  [discuzq]

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/docker-library#44]
**Describe the bug**

The end check version of compnent DiscuzQ is docker compose version  

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

```
 "end_check_versions.stdout_lines": [
        "nginx version: nginx/1.20.2",
        "Docker version 20.10.12, build e91ed57",
        "phpmyadmin version: \"version\": \"5.1.1\",",
        "DiscuzQ version                  \"com.docker.compose.version\": \"2.1.1\",",
        "System version: CentOS 7.9",
        "Image name: websoft9-discuzq3.0-CentOS7.9"
```

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [x] 阿里云
- [x] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by hxinqi** [comment]
/var/www/discuz映射不到宿主机，进入容器查看该目录权限为0

**Comment by xiefei51** [comment]
版本输出的源码在： ansible-discuzq/roles/discuzq/tasks/main.yml
bug原因：输出版本“Check Discuzq Version”的shell命令不对。
通过进入discuzq容器，以正确的版本号进行检索，最终在  /var/www/discuz/vendor/discuz/core/src/Foundation/Application.php  文件下找到正确的版本。
修改：通过  docker exec -it discuzq bash -c 'cmd1 && cmd2'  实现在容器外执行某个容器内的某个命令操作，和相关字符串拼接的命令，成功输出正确格式的版本号。
shell: sudo echo "DiscuzQ version $(docker exec -it discuzq bash -c 'grep -rn "const VERSION =" /var/www/discuz/vendor/discuz/core/src/Foundation/Application.php | awk "{print \$5}" | tr -d ";"')" 1>> /data/logs/install_version.txt
现已上传至dev并测试：
![image](https://user-images.githubusercontent.com/100544684/158090253-d78cfe5c-1d22-4458-8114-069d86ab36a0.png)
