### ISSUE TITLE
Code-Server Run Error

### ISSUE THREAD

**Issue by zhaojing1987** [Websoft9/docker-library#440]
安装后启动报错：
![image](https://github.com/Websoft9/docker-library/assets/7624828/f744fcd1-5766-42f1-afd1-51aabc8ee604)

修正方法：
W9_URL需要写包含完整协议和端口的URL，例如：W9_URL='http://47.92.222.186:9045'

**Comment by lessfrim** [comment]
使用火狐浏览器没有该弹窗，看edge的开发者模式反映是URL的问题
![Z65B)OXKYN{` (%K 2{B$W](https://github.com/Websoft9/docker-library/assets/117550670/a8a5fc54-fe8d-4c10-926b-54cb6331ea7e)
网上找到的类似的与URL有关的问题
<img width="542" alt="1702372994084" src="https://github.com/Websoft9/docker-library/assets/117550670/dc923de5-2322-4daa-9398-c5300508d0b1">
开发者模式指向的有错误的位置也是和上面一样使用了new URL
<img width="480" alt="1702373063496" src="https://github.com/Websoft9/docker-library/assets/117550670/e6e06fce-0b64-4054-b980-a16c9aaa958e">

**Comment by chendelin1982** [comment]
solved
