### ISSUE TITLE
delete url/path to access knowage, access it directly 

### ISSUE THREAD

**Issue by lessfrim** [Websoft9/docker-library#448]
delete url/path to access knowage, access it directly 
前台404
![image](https://github.com/Websoft9/docker-library/assets/117550670/0795e129-222e-4aef-a4d3-be6c4ef48f58)

**Comment by lessfrim** [comment]
前台404
![image](https://github.com/Websoft9/docker-library/assets/117550670/0795e129-222e-4aef-a4d3-be6c4ef48f58)

**Comment by chendelin1982** [comment]
don't need to process
