### ISSUE TITLE
complete docker compose for matomo

### ISSUE THREAD

**Issue by lessfrim** [Websoft9/docker-library#463]
安装时无法连接到数据库：
<img width="980" alt="1701747639942" src="https://github.com/Websoft9/docker-library/assets/117550670/fa59bf1e-ebc1-4e73-b1d9-baa7a200d316">
<img width="656" alt="1701747684393" src="https://github.com/Websoft9/docker-library/assets/117550670/e6fd1ba1-31f3-479b-a4d1-bf57d1e65251">

**Comment by qiaofeng1227** [comment]
${W9_ID}-db change to ${W9_ID}-mysql

**Comment by Camelliw** [comment]
<img width="602" alt="image" src="https://github.com/Websoft9/docker-library/assets/117551145/b109736a-7e28-4d18-be28-b17bcd7fff99">

**Comment by chendelin1982** [comment]
solved
