### ISSUE TITLE
complete docker compose for mattermost

### ISSUE THREAD

**Issue by lessfrim** [Websoft9/docker-library#465]
![D0EZRO R0VA%ZSPT2Q7R(_9](https://github.com/Websoft9/docker-library/assets/117550670/0c62cea5-57e9-43a2-9d2b-6e0b66c28181)

**Comment by Camelliw** [comment]
均无法访问
<img width="837" alt="image" src="https://github.com/Websoft9/docker-library/assets/117551145/16792f5c-4d6c-45b1-802c-f87e70db7e5d">、
<img width="182" alt="image" src="https://github.com/Websoft9/docker-library/assets/117551145/d85a382b-f4d7-420d-b8cc-86cf7edb223a">

**Comment by chendelin1982** [comment]
solved
