### ISSUE TITLE
Improve docker-compose for using latest template   [drupal]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#47]

**Comment by qiaofeng1227** [comment]
1. DB container suggest to use mysql, refer to: https://github.com/Websoft9/docker-mysql/blob/main/docker-compose-production.yml
2. drupal container  refer to :https://registry.hub.docker.com/_/drupal

**Comment by qiaofeng1227** [comment]
![Uploading image.png…]()

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/115172326-9d382200-a0f7-11eb-8afc-0721fd6575bb.png)

**Comment by viafcccy** [comment]
if mount /var/www/html/sites, in guide site can't load DB config web page.
![image](https://user-images.githubusercontent.com/45913187/115327847-3df31400-a1c2-11eb-9d4e-aba08808ced2.png)
