### ISSUE TITLE
complete docker compose for scratch

### ISSUE THREAD

**Issue by auaaaa** [Websoft9/docker-library#474]
latest版本安装失败
![QQ图片20231205141833](https://github.com/Websoft9/docker-library/assets/117525450/65ea3b86-ef37-4706-b280-089e0403d9e2)
![QQ图片20231205141840](https://github.com/Websoft9/docker-library/assets/117525450/c693e3eb-aaa7-4b17-900c-bb2f89deb6a4)

**Comment by auaaaa** [comment]
2023-12-7
安装成功，latest version is 3.0

**Comment by qiaofeng1227** [comment]
solved
