### ISSUE TITLE
complete docker compose for mongocampass

### ISSUE THREAD

**Issue by lessfrim** [Websoft9/docker-library#477]
域名访问无
<img width="713" alt="1701757657988" src="https://github.com/Websoft9/docker-library/assets/117550670/5722051e-9704-4a0e-b102-3bd1cca0245f">
删除域名访问后无 无域名访问
<img width="830" alt="1701757876183" src="https://github.com/Websoft9/docker-library/assets/117550670/76ce2730-9314-4935-8e48-7b67c5ae6460">

**Comment by chendelin1982** [comment]
domain access solved, ip:port refer to: https://github.com/Websoft9/plugin-myapps/issues/24
