### ISSUE TITLE
username and password of Logstash[elk]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#49]
**What type of your feature request?**  

- [ ] xpack.monitoring.elasticsearch.password
- [ ] xpack.management.elasticsearch.password
- [ ] user and passord at pipeline configration file

三个账号的关联关系，必要性

**Comment by laozhou0731** [comment]
ELK 支持多用户，分权管理。数据来源于不同的pipeline，可以为不同的pipeline配置用户，类似某database的用户。系统允许权限更高的用户，用来做多管道或全管道的监控和统一的管理配置：

ELK 安全配置：https://www.elastic.co/guide/en/logstash/current/ls-security.html

- user and passord at pipeline configration file ：管道级别的用户，类似数据库中访问某个database的用户
- xpack.management.elasticsearch.password ： 全局级的管理账号，管道集中配置管理 https://www.elastic.co/guide/en/logstash/7.16/logstash-centralized-pipeline-management.html 
- xpack.monitoring.elasticsearch.password：监控管道运行状态，https://www.elastic.co/guide/en/logstash/7.16/configuring-logstash.html

**Comment by qiaofeng1227** [comment]
1. 对应具体某个elastic输出管道
2. xpack.management.elasticsearch.password
Centralized pipeline management is a subscription feature. If you want to try the full set of features, you can activate a free 30-day trial. So we don't set this group.
3. elastic  user: https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-users.html

**Comment by qiaofeng1227** [comment]
3. elastic  user: https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-users.html

**Comment by chendelin1982** [comment]
最终总结：

理解两个账号的作用，需从 pipeline 的两种存储方式说起：

* 存储在 logstash 中（以文件形式）
* 存储在ES数据库中（官方称之为：[Centralized pipeline management ](https://www.elastic.co/guide/en/logstash/current/configuring-centralized-pipelines.html)）

接下来，解释两个账号的作用：  

一旦采用了 Centralized pipeline management  模式，pipeline 通过 Kibana 创建并保存到 ES，此时 Logstash 工作的时候，就必须主动从 ES 中读取 Pipeline 配置信息，[xpack.management.elasticsearch](https://www.elastic.co/guide/en/logstash/current/configuring-centralized-pipelines.html) 就是这个角色。

pipeline 作为一个项自动化的工作，是有必要对它的工作过程进行监控，同时把工作过程的数据写到 ES，xpack.monitoring.elasticsearch 就是用来做这个的。
