### ISSUE TITLE
can not skip install wizard, and mysql connection error [nopcommerce]

### ISSUE THREAD

**Issue by lessfrim** [Websoft9/docker-library#491]
can not skip install wizard, and mysql connection error
安装失败: 创建数据库: SSL Authentication Error的时候发生错误

**Comment by qiaofeng1227** [comment]
[mysql need 8.0](https://docs.nopcommerce.com/en/installation-and-upgrading/installing-nopcommerce/installing-on-linux.html#install-mysql-server)
