### ISSUE TITLE
complete docker compose for strapi

### ISSUE THREAD

**Issue by auaaaa** [Websoft9/docker-library#493]
域名访问失败
![QQ图片20231205152038](https://github.com/Websoft9/docker-library/assets/117525450/7fcc518b-de13-40be-ab6c-aa86c75bc724)
ip访问失败
![QQ图片20231205152225](https://github.com/Websoft9/docker-library/assets/117525450/0fa3385f-5190-41ff-8c7a-b532c6dd2b14)

**Comment by auaaaa** [comment]
2023-12-7
访问成功
latest version is  v3.6.8

**Comment by qiaofeng1227** [comment]
solved
