### ISSUE TITLE
opencart need replace URL when URL changed

### ISSUE THREAD

**Issue by lessfrim** [Websoft9/docker-library#498]
<img width="478" alt="1701763597939" src="https://github.com/Websoft9/docker-library/assets/117550670/6ae7d739-2cce-41e7-b81f-9b3b9e077ed7">

**Comment by qiaofeng1227** [comment]
W9_URL_REPLACE=true

from domain change to ip:

![image](https://github.com/Websoft9/docker-library/assets/43192516/ec61ffdf-8b3c-419e-b298-34275f695aa5)

**Comment by chendelin1982** [comment]
Not provide this application because Opencart have not official image
