### ISSUE TITLE
complete docker compose for 【teleport】

### ISSUE THREAD

**Issue by auaaaa** [Websoft9/docker-library#500]
latest版本安装失败
![QQ图片20231205161932](https://github.com/Websoft9/docker-library/assets/117525450/8a2738c1-4643-4cbe-82f6-f1a332ece4fb)

**Comment by qiaofeng1227** [comment]
can not login：
![image](https://github.com/Websoft9/docker-library/assets/43192516/983b90ec-d988-4e35-9df5-8b21c474210e)

**Comment by zhaojing1987** [comment]
在/etc/teleport/teleport.yaml 文件中找到：auth_service 加入
```
authentication:
    type: local
    second_factor: off
 ```

**Comment by chendelin1982** [comment]
Have completed, please testing by docs it and need research

- environments from configures?
- 3025 is need mount?  not need for connect Linux
- modify public_addr when docker compose up?
- test application or database.  docs
