### ISSUE TITLE
complete docker compose for discourse

### ISSUE THREAD

**Issue by Camelliw** [Websoft9/docker-library#501]
无域名访问 error
<img width="615" alt="image" src="https://github.com/Websoft9/docker-library/assets/117551145/1d8ec18c-bf16-4371-a6d1-12e70cd48731">

**Comment by chendelin1982** [comment]
不支持非域名访问
![image](https://github.com/Websoft9/docker-library/assets/16741975/5ed416f4-8f48-4c5b-a66a-497faf975519)
