### ISSUE TITLE
complete docker compose for huginn

### ISSUE THREAD

**Issue by lessfrim** [Websoft9/docker-library#504]
无文档
<img width="809" alt="1701764987496" src="https://github.com/Websoft9/docker-library/assets/117550670/638ece12-927e-48d9-b7df-5048b0e1c524">

**Comment by qiaofeng1227** [comment]
how to set password?

default user and password： admin/password

```
SEED_USERNAME=$W9_LOGIN_USER
SEED_PASSWORD=$W9_POWER_PASSWORD
```
