### ISSUE TITLE
complete docker compose for elasticsearch

### ISSUE THREAD

**Issue by Camelliw** [Websoft9/docker-library#515]
缺少访问链接
<img width="697" alt="image" src="https://github.com/Websoft9/docker-library/assets/117551145/5b3606b6-0296-4104-8ff4-f341015de017">

**Comment by chendelin1982** [comment]
![image](https://github.com/Websoft9/docker-library/assets/16741975/6d610e8a-2972-426c-8c39-0ed0f3776ac0)
