### ISSUE TITLE
complete docker compose for espocrm

### ISSUE THREAD

**Issue by Camelliw** [Websoft9/docker-library#517]
<img width="668" alt="image" src="https://github.com/Websoft9/docker-library/assets/117551145/75c55b97-39b4-4594-8b44-13e19a4130ff">
<img width="326" alt="image" src="https://github.com/Websoft9/docker-library/assets/117551145/59084ecd-0205-4d25-8f68-80b45e6dded4">

**Comment by Camelliw** [comment]
```
Run "install" action.
Start EspoCRM installation
error: Installation error, more details:
Error: SQLSTATE[HY000] [1044] Access denied for user 'espocrm_hv6xw'@'%' to database 'espocrm'.
Run "reinstall" action.
Start EspoCRM installation
```

**Comment by qiaofeng1227** [comment]
When use MySQL8.0, need to user root . But if use MariaDB , it OK
Official docs use MariaDB
