### ISSUE TITLE
complete docker compose for zabbix

### ISSUE THREAD

**Issue by auaaaa** [Websoft9/docker-library#519]
- [x] Zabbix server architecture
- [x] Zabbix  depends on software
- [x]  Docker Compose extends

**Comment by qiaofeng1227** [comment]
version problem sovled.

How to import multiple .env from a container?(superset has same problem)

**Comment by zhaojing1987** [comment]
1. Simplified the installation process of Zabbix's docker compose
2. After the normal operation of Zabbix's agent, IP or DNS configuration needs to be done on the web interface

**Comment by zhaojing1987** [comment]
上面配置agent时：
- 如果是ip，ip地址可能会随着容器的重启或者应用的重建发生变化；
- 如果是DNS可以是agent的服务名或者容器名；
![image](https://github.com/user-attachments/assets/67fe5c08-819a-4e74-b115-177e3bd1e9eb)

**Comment by zhaojing1987** [comment]
官方的Docker compose太过复杂，目前已经简化了，但是需要测试不同的操作系统的适配情况，目前只在ubuntu下测试。

**Comment by qiaofeng1227** [comment]
rockylinux下也已经测试

**Comment by chendelin1982** [comment]
- Zabbix Java Gateway
- Zabbix SNMP Traps

add to docker-compose.yml and profiles it?
