### ISSUE TITLE
Check ELK license [elk]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#52]
ELK image license

1. opensource or free
2. redistribution

**Comment by chendelin1982** [comment]
refer to:
* [ELASTIC-LICENSE](https://github.com/elastic/elasticsearch/blob/master/licenses/ELASTIC-LICENSE-2.0.txt)
* [download](https://www.elastic.co/cn/downloads/elasticsearch)

**Comment by chendelin1982** [comment]
ES image include all features, you can set it by `xpack.license.self_generated.type`

* basic (default): to enable basic X-Pack features.（this is free）
* trial: the self-generated license gives access

License limit: You may not provide the software to third parties as a hosted or managed service, where the service provides users with access to any substantial set of the features or functionality of the software.

即不可用于SaaS托管

Note: 后面邮件直接联系了官方，对方表示不可用于 SaaS 托管或镜像
