### ISSUE TITLE
complete docker compose for grafana

### ISSUE THREAD

**Issue by Camelliw** [Websoft9/docker-library#525]
<img width="489" alt="image" src="https://github.com/Websoft9/docker-library/assets/117551145/e03a037b-b17a-4a86-a5c5-a979efc4a288">
<img width="360" alt="image" src="https://github.com/Websoft9/docker-library/assets/117551145/82461c7d-f578-468c-b846-2e60c83de6cb">

**Comment by Camelliw** [comment]
~~~
Error: ✗ failed to connect to database: parse "mysql://grafana_geb9s:AeA5YZd/*~KZa9TA@grafana_geb9s-mysql:3306/grafana_geb9s": invalid port ":AeA5YZd" after host
~~~

**Comment by chendelin1982** [comment]
solved
