### ISSUE TITLE
无法运行 Python 代码，无法连接到note服务器 [TensorFlow] - Nginx

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#529]
**Describe the bug**
![image](https://github.com/Websoft9/docker-library/assets/62225175/419923fe-11aa-4338-a4c3-a429b7c6b9b4)

![企业微信截图_17019088195460](https://github.com/Websoft9/docker-library/assets/62225175/a89507b1-9a31-4f21-8e5d-c99312d5e829)

## Bug source

- [ ] Bugs from installation 
- [x] Bugs from first use
- [ ] Other (You should describe it)

**Comment by chendelin1982** [comment]
Don't use Nginx prxoy, it can running

**Comment by laozhou0731** [comment]
解决方案：
修改 Nginx 容器 全局配置文件 /etc/nginx/conf.d/include/proxy.conf ，添加配置项
```
add_header       X-Served-By $host;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Scheme $scheme;
proxy_set_header X-Forwarded-Proto  $scheme;
proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
proxy_set_header X-Real-IP          $remote_addr;
proxy_pass       $forward_scheme://$server:$port$request_uri;
# 新增配置项
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection upgrade;

```

**Comment by chendelin1982** [comment]
solved
