### ISSUE TITLE
Improve docker-compose for using latest template [elk]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#53]
refer to: https://github.com/Websoft9/docker-elk/blob/main/docker-compose.yml

change container from build Dockerfile to image
- https://hub.docker.com/r/deviantony/elk-logstash
- https://hub.docker.com/r/deviantony/elk-kibana
- https://hub.docker.com/r/deviantony/elk-elasticsearch

**Comment by viafcccy** [comment]
about forked project‘ dockerfile:
**just for multi version**
![image](https://user-images.githubusercontent.com/45913187/115662566-bcda7f00-a371-11eb-9afa-84d807eca4f4.png)

**Comment by viafcccy** [comment]
about environmental values and office docker-install :
elasticsearch
https://www.elastic.co/guide/en/elasticsearch/reference/7.12/docker.html
kibana
https://www.elastic.co/guide/cn/kibana/current/docker.html

**Comment by viafcccy** [comment]
1.针对文件，往往是配置文件的只读陷阱，宿主机项目有配置文件写ro，如果没有配置文件rw。
2.文件挂载方式是bind。

**Comment by viafcccy** [comment]
调研：插件安装

**Comment by viafcccy** [comment]
complete basicly !
to do:
1. multi verion cause bug.
2. install pluin.
3. Add details into the document for user convenience.

**Comment by qiaofeng1227** [comment]
https://github.com/elastic/dockerfiles/blob/7.13/elasticsearch/Dockerfile

**Comment by qiaofeng1227** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/7.12/docker.html

set env【TAKE_FILE_OWNERSHIP】

**Comment by qiaofeng1227** [comment]
[create user method](https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-users.html)
