### ISSUE TITLE
绑定域名无法访问 Object Browser 内容，原生端口访问正常 [Minio] - Nginx

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#530]
**Describe the bug**

websoft9 部署异常
![image](https://github.com/Websoft9/docker-library/assets/62225175/154f3908-86bc-4858-83aa-f21590d1650b)

![image](https://github.com/Websoft9/docker-library/assets/62225175/8b8159e9-b940-4906-8117-70f46d14f64d)

单镜像产品，正常
![image](https://github.com/Websoft9/docker-library/assets/62225175/26f16f19-5d0c-43ef-9469-98c3ce0a4bcf)

## Bug source

- [ ] Bugs from installation 
- [x] Bugs from first use
- [ ] Other (You should describe it)

**Comment by laozhou0731** [comment]
解决方案：
修改 Nginx 容器 全局配置文件 /etc/nginx/conf.d/include/proxy.conf ，添加配置项
```
add_header       X-Served-By $host;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Scheme $scheme;
proxy_set_header X-Forwarded-Proto  $scheme;
proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
proxy_set_header X-Real-IP          $remote_addr;
proxy_pass       $forward_scheme://$server:$port$request_uri;
# 新增配置项
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection upgrade;

```

**Comment by chendelin1982** [comment]
solved
