### ISSUE TITLE
The directory where the container is mounted to the host does not have kahadb [ActiveMQ]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#538]
![image](https://github.com/Websoft9/docker-library/assets/62225175/c7629f08-a572-4f89-8e08-7245f80d1f10)

**Comment by chendelin1982** [comment]
good advice. have fixed
![image](https://github.com/Websoft9/docker-library/assets/16741975/97580e86-7bfd-4a12-92a9-cd6674ceed42)
