### ISSUE TITLE
upgrade to 6.0 for [graylog]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#540]
**What type of your feature request?**  

graylog add new function Data node, it need opensearch, need more check and research

**Comment by qiaofeng1227** [comment]
[official compose ](https://go2docs.graylog.org/current/downloading_and_installing_graylog/docker_installation.htm)

**Comment by zhaojing1987** [comment]
```Graylog 数据节点是 Graylog 5.2 中首次发布的测试版功能。目前，不建议将 Data Node 用于生产环境。```

Graylog 6.0 + 数据节点： [docker compose](https://github.com/Graylog2/docker-compose/tree/main/open-core) 

复杂点：
1、容器启动以后，需要先进行一次basc auth的登录验证，弹出登录对话框，用户名为：admin，但是密码需要通过容器日志查看，它是临时生成；
2、登录以后，需要按照步骤进行初始化，大概是给 数据节点 配置CA 和初始化
3、Graylog 的登录密码，通过环境变量 GRAYLOG_ROOT_PASSWORD_SHA2 设置，需要将原始密码进行加密后赋值
