### ISSUE TITLE
Cannot logout [suitecrm]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#547]
![image](https://github.com/Websoft9/docker-library/assets/62225175/770400a8-9cba-4f21-bcd6-a9ca361114c3)

![image](https://github.com/Websoft9/docker-library/assets/62225175/c4b0e361-e3c4-4b82-af75-c794c13d364f)

**Comment by chendelin1982** [comment]
Yes, I also found this problem
