### ISSUE TITLE
Unable to open editor when posting [DiscuzQ]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#550]
![image](https://github.com/Websoft9/docker-library/assets/62225175/a855142b-4e98-48be-9699-0ca434ac05d0)

**Comment by zhaojing1987** [comment]
故障原因：编辑器文件 lute.min.js 是通过https://dl.discuz.chat/ 在线实时拉取，现在该网站已失效，故拉取不到。
解决方案：将在线拉取该js该为本地拉取。
具体步骤：
1、进入DiscuzQ容器 ,将文件
 [lute.min.js](https://github.com/Websoft9/docker-library/blob/main/apps/discuzq/src/lute.min.js) 
 [dzq.js](https://github.com/Websoft9/docker-library/blob/main/apps/discuzq/src/dzq.js)
 复制到目录：/var/www/discuz/public/js
 2、找到文件：/var/www/discuz/public/_next/static/chunks/pages/thread/post~493df0b3-af2d4863b358d0dc1ef3.js
 将 https://cdn.jsdelivr.net 替换为：https://fastly.jsdelivr.net  (解决有些js加载慢的问题)
 将 https://dl.discuz.chat/discuzq-fe/static/lute 替换为：/js
 3、找到文件：/var/www/discuz/public/index.html
 搜索：dzqjs.src   将其修改为：dzqjs.src = '../js/dzq.js';
 
后台管理页面加载不出的问题：
1、进入DiscuzQ容器 ,将文件夹 https://github.com/Websoft9/docker-library/tree/main/apps/discuzq/src/lib 上传到 var/www/discuz/public/static-admin 目录下
2、找到文件：/var/www/discuz/public/admin.html 将内容：
```
  <script src=https://dl.discuz.chat/lib/vue@2.6.11.min.js></script>
  <script src=https://dl.discuz.chat/lib/vuex@3.2.0.min.js></script>
```
替换为：
```
  <script src=/static-admin/lib/vue@2.6.11.min.js></script>
  <script src=/static-admin/lib/vuex@3.2.0.min.js></script>
```
注释行：
```
  找到行：<script src=https://dl.discuz.chat/dzq/admin.js></script>
  注释：
  <!-- <script src=https://dl.discuz.chat/dzq/admin.js></script> -->
```

后台 “管理中心首页”部分参数加载不出：
![image](https://github.com/Websoft9/docker-library/assets/7624828/ce817a2e-30d1-43b9-854b-49e2a6336fa9)

http://cloud.discuz.chat/latest.js 文件联网加载不到，暂未找到解决方案？暂时不影响其他功能的使用

**Comment by chendelin1982** [comment]
Give it up
