### ISSUE TITLE
improve docker-compose.yml for [kibana],[elasticsearch],[logstash]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#560]
**What type of your feature request?**  

- [ ] which stacks?
- [ ] how to connect it?
- [ ] 抓取数据与数据管道

**Comment by chendelin1982** [comment]
经过调研，每个组件都可以单独运行，故均为单独产品

- [x] kibana   env? how to connect es?
- [x] elasticsearch  env? accounts? token? ssl?
- [x] logstash

**Comment by qiaofeng1227** [comment]
删除elastic，elasticsearch里追加kibana，Logstash 成为一个产品

**Comment by chendelin1982** [comment]
I have implements it, please test it

**Comment by qiaofeng1227** [comment]
elastic：
src directory lose
.env's environment: cluster.name, upper chars? network.host?,discovery.type?
