### ISSUE TITLE
create docker-compose for [syncthing]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#563]
**What type of your feature request?**  

- [ ] [syncthing](https://syncthing.net/)

**Comment by qiaofeng1227** [comment]
https://docs.syncthing.net/intro/getting-started.html

**Comment by chendelin1982** [comment]
test it

**Comment by chendelin1982** [comment]
- docs?  安装，匹对，文件夹
- mount volume: /data/websoft9/syncthing【一台服务器安装两个，第二个无法启动，同一个挂载目录报错，用声明挂载就可以】

**Comment by chendelin1982** [comment]
```
    volumes:
      - $SYNC_PATH/$APP_ID:/var/syncthing
```
