### ISSUE TITLE
Access by Domain, no Route matched with those values. [kong]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#567]
![image](https://github.com/Websoft9/docker-library/assets/16741975/b61a0d86-bc6c-4345-ae29-1029ec840642)

**Comment by chendelin1982** [comment]
1. try delete port at below environments. e.g 0.0.0.0/0
   ```
    KONG_PROXY_LISTEN=0.0.0.0:${W9_HTTP_PORT}
    KONG_ADMIN_LISTEN=0.0.0.0:${W9_ADMIN_API_PORT_SET}
    KONG_ADMIN_GUI_LISTEN=0.0.0.0:${W9_ADMIN_GUI_PORT_SET}
   ```

![image](https://github.com/Websoft9/docker-library/assets/43192516/5e6e5788-3243-417d-b61b-b0550fbe27a0)

2. try to delete W9_ADMIN_API_PORT_SET=8001
![image](https://github.com/Websoft9/docker-library/assets/43192516/0718e3ad-3cdd-4caa-a801-55d0ae74df64)

3.  Add W9_ADMIN_PATH="/adminw76rZ"

**Comment by qiaofeng1227** [comment]
![image](https://github.com/Websoft9/docker-library/assets/43192516/0718e3ad-3cdd-4caa-a801-55d0ae74df64)

**Comment by chendelin1982** [comment]
what this environments?

-  KONG_PROXY_LISTEN
-  KONG_ADMIN_LISTEN
-  KONG_ADMIN_GUI_LISTEN

**Comment by chendelin1982** [comment]
We should know how to access Kong by Nginx Proxy
