### ISSUE TITLE
mautic update to v5.x 

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#587]
update to version5: https://github.com/mautic/docker-mautic/blob/mautic5/examples/basic/docker-compose.yml

**Comment by chendelin1982** [comment]
update to version5: https://github.com/mautic/docker-mautic/blob/mautic5/examples/basic/docker-compose.yml

**Comment by qiaofeng1227** [comment]
使用v4-apache，软件也不能正常运行。

**Comment by qiaofeng1227** [comment]
official compose init can not connect db: https://github.com/mautic/docker-mautic/issues/270
