### ISSUE TITLE
command to change publick IP [erpnext]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#59]
use command to replace
# .env file's [SITE_NAME] should  be changed to public IP or domain name to be accessed by Internet

**Comment by zengxc-1996** [comment]
tested ok:

![image](https://user-images.githubusercontent.com/63622990/119110811-0db6c380-ba55-11eb-8206-de9270ff5a9f.png)

![image](https://user-images.githubusercontent.com/63622990/119110765-04c5f200-ba55-11eb-8290-ca8c3bf6495b.png)

![image](https://user-images.githubusercontent.com/63622990/119111967-2bd0f380-ba56-11eb-824d-f4d5960bad3b.png)
