### ISSUE TITLE
metabase安装报错

### ISSUE THREAD

**Issue by wildechair** [Websoft9/docker-library#595]
![image](https://github.com/Websoft9/docker-library/assets/105709702/71f56db7-521f-40a1-abd9-de4f1866c997)
![image](https://github.com/Websoft9/docker-library/assets/105709702/5f79fcb4-3e1d-46ad-b7ee-bd3462bdb643)

**Comment by wildechair** [comment]
错误详情:failed to deploy a stack: metabase Pulling metabase Error Error response from daemon: manifest for metabase/metabase:0.47.9 not found: manifest unknown: manifest unknown

**Comment by qiaofeng1227** [comment]
更新tag：v0.49.3
