### ISSUE TITLE
mattermost 无法访问

### ISSUE THREAD

**Issue by wildechair** [Websoft9/docker-library#596]
![image](https://github.com/Websoft9/docker-library/assets/105709702/6e2caa04-102b-48b5-968c-79b6615af7bb)
![image](https://github.com/Websoft9/docker-library/assets/105709702/3f07b9f4-4a77-40b1-a84b-aeca93353e6f)
![image](https://github.com/Websoft9/docker-library/assets/105709702/fcff1753-9ab2-4a0f-85af-f74926e00ab5)

**Comment by wildechair** [comment]
容器一直报错重启

**Comment by qiaofeng1227** [comment]
W9_POWER_PASSWORD-->W9_RCODE
