### ISSUE TITLE
Drupal 无法安装

### ISSUE THREAD

**Issue by wildechair** [Websoft9/docker-library#597]
![image](https://github.com/Websoft9/docker-library/assets/105709702/04b3b93a-af29-4381-9585-4e791011fea1)
![image](https://github.com/Websoft9/docker-library/assets/105709702/1777d93a-10ed-4858-bc75-a872c8b321cf)

**Comment by wildechair** [comment]
错误详情:failed to deploy a stack: drupal Pulling drupal Error Error response from daemon: manifest for bitnami/drupal:10.2 not found: manifest unknown: manifest unknown

**Comment by qiaofeng1227** [comment]
tag error:10.2->10.2.5
