### ISSUE TITLE
docker-erpnext can't input email at first time when you log in(ERPNext11,12) [erpnext]

### ISSUE THREAD

**Issue by laotou66** [Websoft9/docker-library#60]
**Describe the bug**

## Bug source
- [ ] Bugs from installation 

## System Environment
**Application Version**
e.g v4.5

**OS**
- [ ] Ubuntu 20.04

**Cloud PlatForm**
- [ ] 腾讯云

运行：sudo docker-compose up -d
安装mariadb 致命错误
Status: Downloaded newer image for mariadb:10.6
Creating erpnext-mariadb        ... done
Creating erpnext-nginx          ... done
Creating erpnext-redis-socketio ... done
Creating erpnext-redis-queue    ... done
Creating erpnext-worker         ... done
Creating erpnext-redis-cache    ... done
Creating erpnext-worker-default ... 
Creating erpnext-schedule       ... error
Creating erpnext-worker-short   ... 
Creating erpnext-worker-default ... error
Creating erpnext-socketio       ... 
Creating erpnext-site-creator   ... 

ERROR: for erpnext-schedule  Cannot start service erpnext-schedule: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "schedule": executable file not found in $PATH: unknown

ERROR: for erpnext-worker-default  Cannot start service erpnext-worker-default: OCI runtime create failed: container_linux.go:367: starting con
Creating erpnext-site-creator   ... error
Creating erpnext-worker-long    ... error
Creating erpnext-socketio       ... done
Creating erpnext-worker-short   ... error

ERROR: for erpnext-worker-long  Cannot start service erpnext-worker-long: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "worker": executable file not found in $PATH: unknown

ERROR: for erpnext-worker-short  Cannot start service erpnext-worker-short: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "worker": executable file not found in $PATH: unknown

ERROR: for erpnext-schedule  Cannot start service erpnext-schedule: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "schedule": executable file not found in $PATH: unknown

ERROR: for erpnext-worker-default  Cannot start service erpnext-worker-default: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "worker": executable file not found in $PATH: unknown

ERROR: for site-creator  Cannot start service site-creator: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "new": executable file not found in $PATH: unknown

ERROR: for erpnext-worker-long  Cannot start service erpnext-worker-long: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "worker": executable file not found in $PATH: unknown

ERROR: for erpnext-worker-short  Cannot start service erpnext-worker-short: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "worker": executable file not found in $PATH: unknown
ERROR: Encountered errors while bringing up the project.

![image](https://user-images.githubusercontent.com/103360136/162612324-4a64a5a8-f27a-4429-ba32-dac4460f0358.png)

**Comment by qiaofeng1227** [comment]
transfer to Websoft9/docker-library#63
