### ISSUE TITLE
OpenSearch 502 Bad Gateway

### ISSUE THREAD

**Issue by wildechair** [Websoft9/docker-library#601]
![image](https://github.com/Websoft9/docker-library/assets/105709702/aa910ce3-e8dd-4e8b-81ed-d18c74a5bc12)

![image](https://github.com/Websoft9/docker-library/assets/105709702/1c3e05ee-a0ef-4848-b304-d732531c75b3)

![image](https://github.com/Websoft9/docker-library/assets/105709702/45171f39-c7ce-4425-b0c7-984489bd2534)

**Comment by qiaofeng1227** [comment]
You should access dashboard
