### ISSUE TITLE
n8n  Init Problem

### ISSUE THREAD

**Issue by wildechair** [Websoft9/docker-library#603]
![image](https://github.com/Websoft9/docker-library/assets/105709702/c4ed4d5c-3c00-4f5b-83e2-e5684b7e52cf)

**Comment by yuval2508** [comment]
> ![image](https://github.com/Websoft9/docker-library/assets/105709702/c4ed4d5c-3c00-4f5b-83e2-e5684b7e52cf)
> 
> 
I've got this same issue running on docker on my macOS

**Comment by chendelin1982** [comment]
@yuval2508 which version of n8n you selected?

**Comment by yuval2508** [comment]
I pulled the latest version from docker hub.
but after I set environment var `N8N_SECURE_COOKIE=false` I've succeeded to use it.

**Comment by chendelin1982** [comment]
> I pulled the latest version from docker hub. but after I set environment var `N8N_SECURE_COOKIE=false` I've succeeded to use it.

good, I have test 1.36.4, it run ok
