### ISSUE TITLE
Discourse run failed

### ISSUE THREAD

**Issue by zhaojing1987** [Websoft9/docker-library#615]
版本：latest

容器状态：
![image](https://github.com/Websoft9/docker-library/assets/7624828/fd794a46-9435-4855-bfca-87d974dbd1b3)

容器日志：
![image](https://github.com/Websoft9/docker-library/assets/7624828/2db25a15-69a8-4806-9a9e-3306b63d8785)

**Comment by qiaofeng1227** [comment]
password use w9_recode and db name and db user use const.
