### ISSUE TITLE
complete docker compose for [Bytebase]

### ISSUE THREAD

**Issue by Camelliw** [Websoft9/docker-library#618]
<img width="616" alt="屏幕截图 2024-05-29 163922" src="https://github.com/Websoft9/docker-library/assets/117551145/57cef658-0d33-4949-a88f-4a2b6a5cb155">

**Comment by qiaofeng1227** [comment]
.env 
```
W9_DIST=community
W9_REPO=bytebase/bytebase
# bytebase image have no tag: latest
W9_VERSION=2.14.1

```
