### ISSUE TITLE
complete docker compose for [Kong]

### ISSUE THREAD

**Issue by Camelliw** [Websoft9/docker-library#621]
配置域名，访问后台有画面。IP访问无响应。
<img width="643" alt="image" src="https://github.com/Websoft9/docker-library/assets/117551145/daf74dc5-1dbe-4214-ba46-6c779d91df3c">

**Comment by qiaofeng1227** [comment]
我的app url带的端口不正确。

**Comment by chendelin1982** [comment]
when add domain after running, nginx-proxy.conf add to Gateway?

**Comment by qiaofeng1227** [comment]
When running by ip，bind the domain，nginx config file can not add to gateway.
