### ISSUE TITLE
complete docker-compose.yml for [nodered]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#622]
**What type of your feature request?**  

- [x] [official architecture](https://nodered.org/) research
- [x] test offcial docker
- [x] complete standardized expression
- [x] developer test and running
- [x] specials and refers at notes.md/.env/docker-compose.yml
- [x] contentful
- [x] test at Appstore and nginx proxy testing
- [x] docs
- [x] siteurl or baseurl
- [x] more environments from: https://nodered.org/docs/getting-started/docker#startup
- [x] connetion URI
- [x] ports
- [x] credentials environment
- [x] i18n
- [x] other

**Comment by qiaofeng1227** [comment]
flows.json,settings.js  in the /data directory.(mounted)
