### ISSUE TITLE
complete docker-compose.yml for [Nexus]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#628]
**What type of your feature request?**  

- [x] [official architecture research](https://github.com/sonatype/docker-nexus3)
- [x] test offcial docker
- [x] complete standardized expression
- [x] developer test and running
- [x] specials and refers at notes.md/.env/docker-compose.yml
- [x] contentful
- [x] test at Appstore and nginx proxy testing
- [x] docs
- [x] siteurl or baseurl
- [x] more environments from
- [x] connetion URI
- [x] ports
- [x] credentials environment
- [x] i18n
- [x] other

**Comment by qiaofeng1227** [comment]
password: https://community.sonatype.com/t/modify-set-admin-password-in-nexus3-sonatype-via-helm-chart/12158
