### ISSUE TITLE
complete docker-compose.yml for [ManageIQ]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#630]
**What type of your feature request?**  

- [x] [official architecture research](https://github.com/ManageIQ)
- [x] test offcial docker
- [x] complete standardized expression
- [x] developer test and running
- [x] specials and refers at notes.md/.env/docker-compose.yml
- [x] contentful
- [x] test at Appstore and nginx proxy testing
- [x] docs
- [x] siteurl or baseurl
- [x] more environments from
- [x] connetion URI
- [x] ports
- [x] credentials environment
- [x] i18n
- [x] other

**Comment by qiaofeng1227** [comment]
[refer to license](https://github.com/ManageIQ/manageiq?tab=readme-ov-file#export-notice)

**Comment by qiaofeng1227** [comment]
need to access by https://domain

**Comment by chendelin1982** [comment]
Nginx proxy for https is need set https?

**Comment by qiaofeng1227** [comment]
目前nginx代理通过https转发。通过域名访问必须配置证书，能否有域名访问不配置证书的方法？nginx做特殊配置？

**Comment by zhaojing1987** [comment]
测试：Kasm Workspaces 和 OpenSearch 这个两个应用本身是https的，但是绑定域名后，可以使用http访问

**Comment by zhaojing1987** [comment]
ManageIQ 测试也可以
