### ISSUE TITLE
complete docker-compose.yml for [portkey]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#634]
**What type of your feature request?**  

[portkey.ai](https://portkey.ai/)

- [x] official architecture research
- [x] test offcial docker
- [x] complete standardized expression
- [x] developer test and running
- [x] specials and refers at notes.md/.env/docker-compose.yml
- [x] contentful
- [x] test at Appstore and nginx proxy testing
- [x] docs
- [x] siteurl or baseurl
- [x] more environments from or configuration file
- [x] connetion URI
- [x] ports
- [x] credentials environment
- [x] i18n
- [x] other

**Comment by qiaofeng1227** [comment]
docker compose refer to: https://github.com/Portkey-AI/gateway/blob/main/docker-compose.yaml

**Comment by qiaofeng1227** [comment]
portkey就是多个LLM的网关汇聚，对外就是一个API，没有可视化界面，用户使用较难。
