### ISSUE TITLE
complete docker-compose.yml for [passbolt]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#635]
**What type of your feature request?**  

https://www.passbolt.com/

- [x] official architecture research
- [x] test offcial docker
- [x] complete standardized expression
- [x] developer test and running
- [x] specials and refers at notes.md/.env/docker-compose.yml
- [x] contentful
- [x] test at Appstore and nginx proxy testing
- [x] docs
- [x] siteurl or baseurl
- [x] more environments from
- [x] connetion URI
- [x] ports
- [x] credentials environment
- [x] i18n
- [x] other

**Comment by qiaofeng1227** [comment]
https://www.passbolt.com/docs/hosting/install/ce/docker/

**Comment by qiaofeng1227** [comment]
是否一定需要stmp才能初始化注册成功？

**Comment by zhaojing1987** [comment]
1、当前数据库连接报错，需要修改环境变量.env和Docker compose中的一致
```
DATASOURCES_DEFAULT_DATABASE=$W9_ID
DATASOURCES_DEFAULT_USERNAME=$W9_ID
```
2、passbolt 按照完成以后，需要执行命令来初始化管理员用户：
```
docker exec 容器名 su -m -c "bin/cake passbolt register_user -u 邮箱 -f 名 -l 姓 -r admin" -s /bin/sh www-data
```
注意：由于没有事先配置smtp，所以，执行完成命令后，会返回一个字符串，例如：
```
/setup/start/b7ee3cf1-256c-402e-8f36-411ae8295d16/2f6bac57-31a4-40c6-9c08-7a0936b08986
```
需要使用应用的url+字符串是做管理员的初始化，例如：
```http://IP:9001/setup/start/b7ee3cf1-256c-402e-8f36-411ae8295d16/2f6bac57-31a4-40c6-9c08-7a0936b08986```
根据提示安装passblot的插件，然后按照步骤进行初始化即可。
3、管理员登录以后，配置smtp服务，然后创建用户(填写用户邮箱)，用户使用邮箱进行注册(一定需要配置smtp，会向邮箱发送邮件验证)

**Comment by chendelin1982** [comment]
modify  english documentation
