### ISSUE TITLE
complete docker-compose.yml for [checkov]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#641]
**What type of your feature request?**  

docs: https://www.checkov.io/4.Integrations/Docker.html

- [x] official architecture research
- [x] test offcial docker
- [x] complete standardized expression
- [ ] developer test and running
- [ ] specials and refers at notes.md/.env/docker-compose.yml
- [ ] contentful
- [ ] test at Appstore and nginx proxy testing
- [ ] docs
- [ ] siteurl or baseurl
- [ ] more environments from
- [ ] connetion URI
- [ ] ports
- [ ] credentials environment
- [ ] i18n
- [ ] other

**Comment by qiaofeng1227** [comment]
close， not antivirus software
