### ISSUE TITLE
test replace url when using domain for [wordpress]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#659]
**What type of your feature request?**  

test replace url when using domain for wordpress

**Comment by qiaofeng1227** [comment]
flow:
1. install wordpress by wordpress.test2.websoft9.cn,and complete the wizard
2. add domain change.test2.websoft9.cn
3. delete domain to wordpress.test2.websoft9.cn

![image](https://github.com/user-attachments/assets/53983aad-33cc-4696-92dd-a6f6f8ce73e0)

![image](https://github.com/user-attachments/assets/22df7315-7750-42a5-b78d-7b13badee6fc)

**Comment by qiaofeng1227** [comment]
bind multiply domains，it can not be accessed by all of the domains.

**Comment by zhaojing1987** [comment]
Wordpress更改域名新方法，可以不使用当前的解决方案Wordpress的cli 
在环境变量新增代码：
```
environment:
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', getenv('WP_HOME'));
        define('WP_SITEURL', getenv('WP_SITEURL'));
      WP_HOME: http://$W9_URL
      WP_SITEURL: http://$W9_URL
```
可能的问题：WordPress的后台配置域名时为只读状态，不可修改，但是我通过Websoft9的域名管理功能进行修改
![企业微信截图_1723108174383](https://github.com/user-attachments/assets/d1d3bb9d-d6f9-4cbe-9758-41e1e2c8e249)

**Comment by qiaofeng1227** [comment]
初始安装wordpress，完成初始化，使用IP和端口访问：
![image](https://github.com/user-attachments/assets/d53fd5db-2385-4437-b8f6-da9f90d387e0)
![image](https://github.com/user-attachments/assets/c5344569-9526-4be1-bdc2-0e86cead567b)



绑定域名后：
![image](https://github.com/user-attachments/assets/dd02ba27-7379-4730-b05b-dccc00221038)
![image](https://github.com/user-attachments/assets/9e5ad209-0c33-4815-82c5-83a2d3277455)


删除域名：
![image](https://github.com/user-attachments/assets/fc517aa3-07cd-48eb-9e34-22e784e84175)
无法访问wordpress页面，因为W9_URL没有带端口

**Comment by qiaofeng1227** [comment]
总结：使用cli可以同时改变数据库和页面的url; 不使用cli，使用环境变量只能改变页面url，数据库的值为第一次设定值，不会再改变，同时还存在一个websoft9的通用bug，当删除域名后，w9_url没有带端口导致wordpress无法访问。
