### ISSUE TITLE
complete docker-compose.yml for [pmm] ￥50

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#661]
**What type of your feature request?**  

[Percona Monitoring and Management (PMM) ](https://hub.docker.com/r/percona/pmm-server) is an open source observability, monitoring, and management tool for MySQL, PostgreSQL, and MongoDB.

- [x] official architecture research
- [x] test offcial docker
- [x] complete standardized expression
- [x] developer test and running
- [x] specials and refers at notes.md/.env/docker-compose.yml
- [x] contentful
- [x] test at Appstore and nginx proxy testing
- [x] docs
- [x] siteurl or baseurl
- [x] more environments from or configuration file
- [x] connetion URI
- [x] ports
- [x] credentials environment
- [x] i18n
- [x] other

**Comment by chendelin1982** [comment]
![image](https://github.com/user-attachments/assets/bbb1dd0b-4984-44ef-b850-108e33d26112)
 Test ok, it need HTTPS access

**Comment by chendelin1982** [comment]
https?

**Comment by qiaofeng1227** [comment]
确认https，文档也相应修改。

**Comment by chendelin1982** [comment]
need to add nginx-proxy.conf
```
http {
    map $scheme $redirect_scheme {
        https https://pmm.test2.websoft9.cn/;
        default http://pmm.test2.websoft9.cn/;
    }

    server {
        listen 80;
        server_name pmm.test2.websoft9.cn;

        location / {
            proxy_pass https://pmm:9090;  # 代理到你的 HTTPS 容器
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # 处理重定向
            proxy_redirect $redirect_scheme http://pmm.test2.websoft9.cn/;
        }
    }
}

```

**Comment by zhaojing1987** [comment]
默认是使用https的443 端口，也可以直接使用http的 80 端口；
[官方文档](https://docs.percona.com/percona-monitoring-and-management/setting-up/server/docker.html#run-docker-with-data-container)
![image](https://github.com/user-attachments/assets/18838f8a-1c7a-432a-8175-80e973a38a04)

**Comment by qiaofeng1227** [comment]
1. use W9_HTTP_PORT=80
2. edit documentation, delete content about https
