### ISSUE TITLE
complete docker-compose.yml for [vaultwarden] ￥50

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#667]
**What type of your feature request?**  

- [x] official architecture research
- [x] test offcial docker
- [x] complete standardized expression
- [x] developer test and running
- [x] specials and refers at notes.md/.env/docker-compose.yml
- [x] contentful
- [x] test at Appstore and nginx proxy testing
- [x] docs
- [x] siteurl or baseurl
- [x] more environments from or configuration file
- [x] connetion URI
- [x] ports
- [x] credentials environment
- [x] i18n
- [x] other

**Comment by qiaofeng1227** [comment]
https://hub.docker.com/r/vaultwarden/server
https://www.vaultwarden.net/

**Comment by chendelin1982** [comment]
- [x] - add https settings links and reason at initial docs
- [x] - W9_RCODE=$W9_POWER_PASSWORD
