### ISSUE TITLE
Bug  for  memcached

### ISSUE THREAD

**Issue by yuanssssss** [Websoft9/docker-library#669]
**Describe the bug**

When start the gui port on memcached-admin, the bug occured. the GUI page access failure.

![image](https://github.com/user-attachments/assets/bd8bd065-cd05-4b74-b31f-e84ea5ce0e58)

## Bug source

- [x] Bugs from first use

## System Environment

**Application Version**

v1.6

**Comment by qiaofeng1227** [comment]
port type error，should be int，now is string

**Comment by chendelin1982** [comment]
solved
