### ISSUE TITLE
complete docker-compose.yml for [youtrack] 

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#676]
**What type of your feature request?**  

- [x] [official architecture](https://www.jetbrains.com/zh-cn/youtrack/) research
- [x] test offcial docker
- [x] complete standardized expression
- [x] developer test and running
- [x] specials and refers at notes.md/.env/docker-compose.yml
- [x] contentful
- [x] test at Appstore and nginx proxy testing
- [x] docs
- [x] siteurl or baseurl
- [x] more environments from or configuration file
- [x] connetion URI
- [x] ports
- [x] credentials environment
- [x] i18n
- [x] other

**Comment by qiaofeng1227** [comment]
https://www.jetbrains.com/legal/docs/youtrack/license/

**Comment by chendelin1982** [comment]
optimize english docs
