### ISSUE TITLE
After the successful installation getting Internal Server Error on Browser  [erpnext]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#69]
**Describe the bug**

We just used your WebSoft9 installer to install an instance on ERPNext on a server (Ubuntu 18.04). The instance seems to have installed well (Python, nginx, Docker, etc.). The only problem is that some of the ERPNext worker processes and the site-creator service are not starting (even with repeated startup and shutdown of Docker) and as such the installation does not get to the login page to enable the creation of the account. (We get a 502 nginx error at the URL - https://*****.com/.) All the processes start up when Docker is started except for the ones shown below:

 ⠦ Container erpnext-worker-default  Starting                                                                                                                                                                 5.7s
 ⠦ Container erpnext-worker-short    Starting                                                                                                                                                                 5.7s
 ⠦ Container erpnext-worker-long     Starting                                                                                                                                                                 5.7s
 ⠿ Container erpnext-socketio        Started                                                                                                                                                                  0.0s
 ⠦ Container erpnext-site-creator    Starting                                                                                                                                                                 5.7s
 ⠦ Container erpnext-schedule        Starting                                                                                                                                                                 5.7s
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "new": executable file not found in $PATH: unknown
We have saved the logs to enable some guidance on this problem. We would like to get some support for this to get it working. Please advise on how we can get the support. Thank you.

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
transfer to Websoft9/docker-library#63
