### ISSUE TITLE
update ERPNext to version15 for ￥100

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#691]
1. image from frappe/erpnext-worker change to frappe/erpnext

**Comment by zhaojing1987** [comment]
[ERPNext-Docker项目地址](https://github.com/frappe/frappe_docker)
[官方docker-compose](https://github.com/frappe/frappe_docker/blob/main/pwd.yml)
[官方环境变量](https://github.com/frappe/frappe_docker/blob/main/example.env)
经测试该docker-compose文件直接匹配V15 V14 V13版本

容器：erpnext-configurator 和 erpnext-create-site 状态都为 ： exited - code 0 时 表示初始化已经完成，可以通过IP:端口访问

**Comment by qiaofeng1227** [comment]
convert to w9 rule.

**Comment by chendelin1982** [comment]
solved
