### ISSUE TITLE
some errors of flowise on AWS ubuntu

### ISSUE THREAD

**Issue by HTGZYY** [Websoft9/docker-library#693]
软件不断restarting

![e7bd62c7d399a019f8bb318afd9b510](https://github.com/user-attachments/assets/09b4e380-5473-41e8-996f-e13bd6eb0283)

![ca27cc1cdea1bcf0fa02c5b410e6057](https://github.com/user-attachments/assets/7c2f48f3-e66f-4407-bb2c-816aeb16e583)

**Comment by zhaojing1987** [comment]
将docker compose的：
command: /bin/sh -c "sleep 3; flowise start"
修改为：
entrypoint: /bin/sh -c "sleep 3; flowise start"
