### ISSUE TITLE
QuickStart-package install error[erpnext]

### ISSUE THREAD

**Issue by gbanach** [Websoft9/docker-library#70]
After type in command line: 
sudo wget -N https://raw.githubusercontent.com/Websoft9/StackHub/main/docker-installer.sh; sudo bash docker-installer.sh -r erpnext -p

received info: "variables.json has an undefined parameter"
and thats all.

## Deployment method

- [x] All-in-one Installer

## Bug source

- [x] Bugs from installation 

## System Environment
**OS**

- [x] Ubuntu22.04.1

**Cloud PlatForm**

- [x] Other: KVM on Ubuntu 20.04LTS

**Comment by chendelin1982** [comment]
hello, you can refer to: https://github.com/Websoft9/docker-library#how-to-use-it

There no QuickStart-package install now for this repository
