### ISSUE TITLE
Cannot upgrade ERPNext and Frappe Framework [ERPNext]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#715]
**Describe the bug**
Unable to upgrade ERPNext and Frappe Framework through git pull .
ERPNext installed directly from a virtual machine will not encounter this error during the upgrade process

```
进入主容器
cd apps/frappe
git pull
cd ../erpnext
git pull
cd ~/frappe-bench
bench use  erpshanghai.redexglass.com //切换到当前网站
bench migrate
bench setup requirements  
bench build --force
bench clear-cache
docker restart 主容器

```

## Bug source

- [ ] Bugs from installation 
- [x] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**CPU**

- [ ] amd64, x86 
- [ ] arm64
- [ ] Other (You should describe it)   

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
初始安装的版本：
![image](https://github.com/user-attachments/assets/0abf529c-aa98-4dbd-844d-fbfe71e44335)

**Comment by qiaofeng1227** [comment]
目前升级后程序运行正常。
