### ISSUE TITLE
After installing the app, the system encountered a server error [ERPNext]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#716]
**Describe the bug**
After installing the app, the system encountered a server error.
ERPNext installed directly from a virtual machine will not encounter this error when installing  app

```
// install  app
bench get-app https://gitee.com/yuzelin/erpnext_chinese.git
bench install-app  erpnext_chinese

bench get-app --branch version-15 https://gitee.com/yuzelin/erpnext_oob.git
bench install-app  erpnext_oob

bench migrate
bench build --force
bench clear-cache
bench restart

```

## Bug source

- [ ] Bugs from installation 
- [x] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**CPU**

- [ ] amd64, x86 
- [ ] arm64
- [ ] Other (You should describe it)   

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
容器内安装余总的app可能存在不兼容
