### ISSUE TITLE
nginx config problem on suitecrm

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#717]
cannot show menu by domain
![image](https://github.com/user-attachments/assets/5498846c-69fa-4351-ab20-fe37b063b2a8)

It is ok by ip 
![image](https://github.com/user-attachments/assets/b0bc4aee-5085-4a79-a62f-e3d9d8d8b70d)

**Comment by zhaojing1987** [comment]
src 目录下新建文件：nginx-proxy.conf，配置如下：
```
proxy_busy_buffers_size     512k;
proxy_buffers  4 512k;
proxy_buffer_size 256k;
```
