### ISSUE TITLE
docuseal how  to sign by a document for ￥50

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#723]
docuseal how to sign to a PDF file

**Comment by czj69233** [comment]
DocuSeal实现电子签名：
进入首页后，点击右上角的CREATE选择创建文档
![image](https://github.com/user-attachments/assets/43c25203-3edd-4d43-a34e-782afcc373b3)
创建成功后点击屏幕中心的上传可以选择上传文档、图片等，在此处我选择的是上传PDF文档
![image](https://github.com/user-attachments/assets/c6364b2c-f24f-49cb-a2cb-da65f7bb8766)
上传成功后将右方的Signature拖拽至想要在文档上显示的位置，之后点击“SIGN YOURSELF“进行签名
![image](https://github.com/user-attachments/assets/0893233f-f3a0-4bf3-a1f1-045d262bc57a)
在签名页面完成签名后点击”SIGN AND COMPLETE“就可以完成签名，最后点击下载即可
![image](https://github.com/user-attachments/assets/c212349c-accb-4da6-8ed8-f19bbf3f6e88)
