### ISSUE TITLE
add sub cli command forn push repository at apphub

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#725]
## request

add sub cli command forn push application's repository

1. `git clone` 
    ```
   #1 git from private repository
   git clone https://myuser:mypassword@websoft9-git/websoft9/wordpress_77juue - repo.git

   #2 git from docker-library repository
    ```
3. Filter the .env and Cover application folder/ from application's repository
  - add
  - delete：W9_APP_NAME
  - keep same, not edit
    - W9_URL
    - W9_ID
    - *_PORT_SET
5. PR
6. delete all temp repository

```
apphub subimt --appid  --github_token
```

**Comment by zhaojing1987** [comment]
已完成开发，并提交，可以进行测试：
命令：apphub commit --appid *** --github_token ***

**Comment by chendelin1982** [comment]
completed
