### ISSUE TITLE
update meta data of variables.json for ￥50

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#726]
- apps/*/variables.json
- change **docker_url** to **version_from**
- pull request to dev branch

**Comment by jinsheng200303** [comment]
### update meta data of variables.json

> 在apps/*/variables.json以及template/variables.json中
实现“change docker_url to version_from”，具体方案记录如下：
#### 方案一

> 利用shell脚本进行文本替换，具体指令如下：
~~~
sed -i '' 's/docker_url/version_from/g' ./*/variables.json
~~~
#### 方案二
> 利用VSCode文本全局替换功能，操作界面如下：
<img width="352" alt="image" src="https://github.com/user-attachments/assets/1f00b254-0928-43d2-929a-bf5378dfabbe">
