### ISSUE TITLE
Improve docker-compose for ...[gitlab]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#73]

**Comment by qiaofeng1227** [comment]
1. refer to:https://github.com/Websoft9/docker-gitlab/blob/main/docker/docker-compose.yml
2. you can get a complete docker-compose file by runnig the below [one installer](https://about.gitlab.com/install/#ubuntu) script

```
curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/escript.deb.sh | sudo bash
```
3. try to get the complete docker-compose file from a  permanent URL
4. database port expose to host
5. other performance tool, e.g redis...?

**Comment by viafcccy** [comment]
1.about gitlab'stack-components that can help us to learn about gitlab.  
https://github.com/Websoft9/ansible-gitlab/blob/main/docs/zh/stack-components.md
2.office gitlab-docker introduce: 
https://docs.gitlab.com/omnibus/docker/README.html#install-gitlab-using-docker-compose

**Comment by chendelin1982** [comment]
精准需求结论参考：Notes.md，compose文件已测试可用，一致性和其他方面优化需后续流程改进

**Comment by qiaofeng1227** [comment]
external_url is required items of env？Gitlab can running when external_url is null, but is there have other problem, you should test it

**Comment by qiaofeng1227** [comment]
gitlab.yml
```

# This file is managed by gitlab-ctl. Manual changes will be
# erased! To change the contents below, edit /etc/gitlab/gitlab.rb
# and run `sudo gitlab-ctl reconfigure`.

production: &base
  #
  # 1. GitLab app settings
  # ==========================

  ## GitLab settings
  gitlab:
    ## Web server settings (note: host is the FQDN, do not include http://)
    host: gitlab.example.com
    port: 80
    https: false

    # The maximum time unicorn/puma can spend on the request. This needs to be smaller than the worker timeout.
    # Default is 95% of the worker timeout
    max_request_duration_seconds: 57

    # Uncommment this line below if your ssh host is different from HTTP/HTTPS one
    # (you'd obviously need to replace ssh.host_example.com with your own host).
    # Otherwise, ssh host will be set to the `host:` value above
    ssh_host:

    # If your ssh user differs from the system user, you need to specify it here
    # Set it to an empty string to omit the username from any ssh url altogether
    ssh_user:

    # WARNING: See config/application.rb under "Relative url support" for the list of
    # other files that need to be changed for relative url support
    relative_url_root:

    # Trusted Proxies
    # Customize if you have GitLab behind a reverse proxy which is running on a different machine.
    # Add the IP address for your reverse proxy to the list, otherwise users will appear signed in from that address.
    trusted_proxies:

```

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/127734127-a532fb4d-64ec-41bd-ae7c-e2854eb2024b.png)

**Comment by qiaofeng1227** [comment]
将gitlab.yml host改成IP地址，即可git clone成功

**Comment by qiaofeng1227** [comment]
init password? refer to [gitlab configuration file](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template)
```ruby
#### Change the initial default admin password and shared runner registration tokens.
####! **Only applicable on initial setup, changing these settings after database
####!   is created and seeded won't yield any change.**
# gitlab_rails['initial_root_password'] = "password"
# gitlab_rails['initial_shared_runners_registration_token'] = "token"
```

**Comment by qiaofeng1227** [comment]
```
```
[root@iZbp1g7srzyyzu8qfaomzxZ docker-jenkins]# git clone http://119.28.5.240/root/test.git
Cloning into 'test'...
fatal: repository 'http://119.28.5.240/root/test.git/' not found
[root@iZbp1g7srzyyzu8qfaomzxZ docker-jenkins]# git clone http://119.28.5.240:9001/root/test.git
Cloning into 'test'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
```
