### ISSUE TITLE
can not connet rpc in aria2 for ￥50

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#735]
![image](https://github.com/user-attachments/assets/350503de-8847-422d-9ab9-c9b23ab4c304)
![image](https://github.com/user-attachments/assets/0762a2f0-a824-4008-bcda-8dd324873651)

**Comment by cbnb233** [comment]
The access key given by the label cannot be used normally, resulting in aria2 being unable to connect normally. After inspection, the instruction RPC_SECRET=$W9_POWER_PASSWORD in the docker-compose.yml file is the initialized key value. However, the initialization of $W9_POWER_PASSWORD is not found in the.env file. After adding the initialization, aria2 can be connected normally.
