### ISSUE TITLE
无法使用语音聊天 [Mattermost]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#736]
**Describe the bug**

设置域名、配置https后，成员间无法使用语音聊天，websocket连接异常

![企业微信截图_17298266086387](https://github.com/user-attachments/assets/582dae86-f719-44da-ac41-d62b215f8b52)

## Bug source

- [ ] Bugs from installation 
- [x] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**CPU**

- [x] amd64, x86 
- [ ] arm64
- [ ] Other (You should describe it)   

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by zhaojing1987** [comment]
1、使用域名且配置https
2、修改环境变量,env,
```
DOMAIN=$W9_URL
MM_SERVICESETTINGS_SITEURL=https://${DOMAIN}
```
