### ISSUE TITLE
 How to install Third party apps[Odoo]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#744]
**Describe the bug**

[Third party apps](https://apps.odoo.com/apps/modules)

install Accouting on Odoo 18
[Odoo 18 Accounting](https://apps.odoo.com/apps/modules/18.0/om_account_accountant)

## Bug source

- [ ] Bugs from installation 
- [x] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**CPU**

- [x] amd64, x86 
- [ ] arm64
- [ ] Other (You should describe it)   

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by zhaojing1987** [comment]
安装步骤：
1、下载第三方应用的zip包
2、将zip包上传到： odoo_addons:/mnt/extra-addons  挂载目录
3、解压该zip包，注意不要文件夹嵌套了(直接使用unzip)
4、重启odoo服务
5、登录odoo，进入 设置，激活开发者模式：
![image](https://github.com/user-attachments/assets/44a2c943-6349-43fe-b03f-1acc687ebefe)
6、更新应用程序列表：在列表将看到导入了第三方应用
![image](https://github.com/user-attachments/assets/829cdf9b-5607-4c44-8421-9420ebab0500)
7、启用
![image](https://github.com/user-attachments/assets/b90b81ce-59bc-440c-a2a7-d10e50b7c893)

**Comment by chendelin1982** [comment]
add it to docs
