### ISSUE TITLE
Update version to [24.9] for [clickhouse] for ￥50

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#757]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub subimt --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by jinsheng200303** [comment]
###  docker logs
~~~
docker logs clickhouse_im92p
~~~
```
/entrypoint.sh: create new user 'admin' instead 'default'
ClickHouse Database directory appears to contain a database; Skipping initialization
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/extra_config.xml'.
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
```
###  sreenshoot
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/6940548b-47cd-4d87-8678-487be5499311">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e3370305-86d0-49f7-adf3-728266f3606b">

**Comment by jinsheng200303** [comment]
## 二次测试
```
修改docker-compose.yml，增加cap_add:- SYS_NICE，解决日志中报错get_mempolicy: Operation not permitted
```
~~~
services:
--
  | clickhouse:
  | image: $W9_REPO:$W9_VERSION
  | container_name: $W9_ID
  | cap_add:
  | - SYS_NICE
.....

~~~

### docker logs
~~~
docker logs clickhouse_n7sl5
~~~
```
/entrypoint.sh: create new user 'admin' instead 'default'
ClickHouse Database directory appears to contain a database; Skipping initialization
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/extra_config.xml'.
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
```
### screenshoot
![Image](https://github.com/user-attachments/assets/a1fd4e86-dc76-4887-84bc-4f5bf226b5e9)

![Image](https://github.com/user-attachments/assets/32c2be58-0240-4e5d-853a-d21ddf17e2a3)
