### ISSUE TITLE
Update version to [v24.0.4] for [dgraph] ¥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#761]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub subimt --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by jinsheng200303** [comment]
### docker logs
~~~
docker logs dgraph_o2m66
~~~
```
2024/10/31 06:21:35 Listening on :8000...
```
### sreenshoot
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e542a018-3638-4b71-acaf-d24865a77edd">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/bbfc71cd-9663-4b1b-b923-67a5c312c4f8">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/1c4e542c-46d9-49c3-a706-d84772a95e07">

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/f6c4a211-3204-4634-8b28-490a2e0ff942">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/5185f320-1599-4442-82fd-4eb3ac9f3b8a">
