### ISSUE TITLE
Update version to [5.8] for [emqx] ¥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#777]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub subimt --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by jinsheng200303** [comment]
### docker logs
~~~
docker logs emqx_rtlpp
~~~
```
WARNING: Default (insecure) Erlang cookie is in use.
WARNING: Configure node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
WARNING: NOTE: Use the same cookie for all nodes in the cluster.
EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
EMQX_NODE__NAME [node.name]: emqx@172.18.0.9
Listener tcp:default on 0.0.0.0:1883 started.
Listener ssl:default on 0.0.0.0:8883 started.
Listener ws:default on 0.0.0.0:8083 started.
Listener wss:default on 0.0.0.0:8084 started.
Listener http:dashboard on :18083 started.
EMQX 5.8.1 is running now!
```
### sreenshoot
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/00491ffe-9f46-469a-9c3c-acbf3b9b3562">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/8127e9de-9b4b-4be8-a3f5-c5d267b02299">

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/b518599e-b083-4ccc-a350-2e4cfd9f74aa">
