### ISSUE TITLE
Update version to [2.1.3] for [flowise] ￥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#779]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub subimt --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by czj69233** [comment]
### docker logs:
```
2024-10-31 07:05:50 [INFO]: Starting Flowise...
2024-10-31 07:05:50 [INFO]: 📦 [server]: Data Source is initializing...
2024-10-31 07:05:54 [INFO]: 📦 [server]: Data Source has been initialized!
2024-10-31 07:05:54 [INFO]: ⚡️ [server]: Flowise Server is listening at :3000
```
### screenshoot:
![image](https://github.com/user-attachments/assets/5e274501-4754-470a-b0cb-e70a21614c79)
![image](https://github.com/user-attachments/assets/4b9b7c69-0df6-49d1-8b92-f4e6e0bf0649)
![image](https://github.com/user-attachments/assets/298f5142-49fc-4daf-b41f-750d3dadc569)
