### ISSUE TITLE
Update version to [3.0] for [haproxy] ¥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#791]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub subimt --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by jinsheng200303** [comment]
### docker logs
~~~
docker logs haproxy_y1k5n
~~~
```
[NOTICE]   (1) : New worker (9) forked
[NOTICE]   (1) : Loading success.
[ALERT]    (9) : sendmsg()/writev() failed in logger #1: No such file or directory (errno=2)
```
### sreenshoot
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/314989a2-5c84-4a29-a793-2268651918b9">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/a154b225-9b59-4c2f-bfb0-0435a12c97f3">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/bcf66780-3338-4a10-8cef-2e2d94e4af8d">
