### ISSUE TITLE
Update version to [v12.2.3] for [postgrest] ¥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#800]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub subimt --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by jinsheng200303** [comment]
### docker logs
~~~
docker logs postgrest_kc7g2
~~~
```
null
```
### docker logs
~~~
docker ps
~~~
```
cf130272b355   postgrest/postgrest:v12.2.3               "/bin/postgrest"         22 minutes ago      Restarting (132) 44 seconds ago                                                                                                                             postgrest_kc7g2
```
### sreenshoot
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/5a39eade-0bb1-4491-864a-cdca9250bcf3">

**Comment by jinsheng200303** [comment]
## 二次测试
```
本次测试新版本，未曾出现之前的报错信息
```
### docker logs
~~~
docker logs postgrest_mmeuc
~~~
```
04/Nov/2024:03:36:47 +0000: Starting PostgREST 12.2.3...
04/Nov/2024:03:36:47 +0000: Listening on port 3000
04/Nov/2024:03:36:47 +0000: Successfully connected to PostgreSQL 16.4 (Debian 16.4-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
04/Nov/2024:03:36:47 +0000: Config reloaded
04/Nov/2024:03:36:47 +0000: Listening for notifications on the "pgrst" channel
04/Nov/2024:03:36:47 +0000: Schema cache queried in 2.6 milliseconds
04/Nov/2024:03:36:47 +0000: Schema cache loaded 0 Relations, 0 Relationships, 0 Functions, 0 Domain Representations, 4 Media Type Handlers, 1196 Timezones
```
### screenshoot
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/f2ea2cbf-ef1e-41ab-8500-030da490e62b">
