### ISSUE TITLE
Update version to [2.58] for [redisinsight] ¥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#807]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub subimt --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by jinsheng200303** [comment]
### docker logs
~~~
docker logs redisinsight_x2ott
~~~
```
Running docker-entry.sh
```
### sreenshoot
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/56da0774-fd16-4d9e-b796-7ab330852dad">

#### 新版本界面UI有所更新，需要对应更新文档

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/6628f08a-06a8-40b3-8312-bcbe78a23dd1">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/967cd7f7-ef39-48fe-b574-d30eae9af63e">
