### ISSUE TITLE
Update version to [v2.7.2] for [redpandaconsole] 10￥

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#808]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub subimt --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by cbnb233** [comment]
登录
![image](https://github.com/user-attachments/assets/1a81c45e-1952-42af-922a-9e6ecc81c415)
docker logs redpandaconsole_zlu4k：
```
     
INF msg=config filepath is not set, proceeding with options set from env variables and flags

INF ts=2024-10-31T08:49:36.254Z msg=started Redpanda Console version=v2.7.2 built_at=1725620020

INF ts=2024-10-31T08:49:36.255Z msg=connecting to Kafka seed brokers, trying to fetch cluster metadata

INF ts=2024-10-31T08:49:36.281Z msg=successfully connected to kafka cluster advertised_broker_count=1 topic_count=0 controller_id=0 kafka_version=v3.6

INF ts=2024-10-31T08:49:37.556Z msg=Server listening on address address=[::]:8080 port=8080

```
