### ISSUE TITLE
Update version to [3.2] for [traefik] ¥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#824]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub subimt --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by jinsheng200303** [comment]
### docker logs
~~~
docker logs traefikproxy_85rax
~~~
```
time="2024-11-01T07:58:22Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
```

### sreenshoot
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/6c738aaf-0919-4803-aa00-938f194c7c49">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/5c960bdd-ea4b-4d5a-82ba-3e35116a7bfb">
