### ISSUE TITLE
Update version to [0.56.2] for [trivy] 10￥

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#826]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub subimt --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by cbnb233** [comment]
进入容器，扫描：
![image](https://github.com/user-attachments/assets/e85e74a6-5ddd-4191-a1b9-ef7511db7b33)
换个路径：
![image](https://github.com/user-attachments/assets/8fea66cf-ed0e-4818-bdac-1dd8c1aa7ef3)
无日志输出
提供的文档有误，没有访问页面
