### ISSUE TITLE
Update version to [23] for [nodejs] 10￥

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#886]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by cbnb233** [comment]
更新版本应为23，22以及-slim和-alpine版本
22版本检验：
![image](https://github.com/user-attachments/assets/e4af933f-44a9-4c42-b698-2136712207aa)
23检测：
![image](https://github.com/user-attachments/assets/5e9a706d-5152-41b4-844c-312afaa65db9)
日志：
```
Add your CI code here, below is example
```
