### ISSUE TITLE
complete docker-compose.yml for [php-fpm]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#935]
**What type of your feature request?**  

- [ ] [official architecture research](https://dockerhub.websoft9.com/_/php)  9000 port, not 80
- [ ] test offcial docker
- [ ] complete standardized expression
- [ ] developer test and running
- [ ] specials and refers at notes.md/.env/docker-compose.yml
- [ ] contentful
- [ ] test at Appstore and nginx proxy testing
- [ ] docs
- [ ] siteurl or baseurl
- [ ] more environments from or configuration file
- [ ] connetion URI
- [ ] ports
- [ ] credentials environment
- [ ] i18n
- [ ] other

**Comment by chendelin1982** [comment]
```
    location / {
        fastcgi_pass   $server:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }
```
It can running, but error from browser `file not found`

**Comment by zhaojing1987** [comment]
nginx高级配置：
```
root   /var/www/html;
location / {
        fastcgi_pass   $server:$port;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }
```

已经测试wordpress，可以正常安装和访问：http://php.test2.websoft9.cn/wordpress/
