### ISSUE TITLE
share screen faied for [screego]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#940]
**Describe the bug**

I have set https for Screengo, but it also share screen failed.

**Comment by cbnb233** [comment]
在测试机上安装screego：
![image](https://github.com/user-attachments/assets/07150c36-0f3f-40e9-98ed-f5c7a33a7d48)
为screego 应用设置 HTTPS 访问：
![image](https://github.com/user-attachments/assets/ec952d26-061d-4d85-a303-01a1808e7749)
修改为真实的邮箱地址，等待一会
访问 screego 的主界面，点击 CREATE OR JOIN A ROOM 创建一个房间
![image](https://github.com/user-attachments/assets/c37ebada-20af-4afe-ac39-561eb6221229)
正常使用
