### ISSUE TITLE
Nginx 转发异常[magento]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#95]
#### 背景
- 端口映射：9001:8080
- 环境设置：MAGENTO_HOST=$APP_URL:$APP_HTTP_PORT ,     APP_URL= IP

#### 现象
- 用 IP:9001 访问，前后台正常访问，页面链接访问正常 
- 用 Nginx 转发 IP:9001 至 80 端口 ，首页正常访问； 后台 IP/admin 及 首页部分菜单、链接无法打开，但用 ip:9001 能正常打开 
- 绑定域名，访问效果：dns:9001 能正常访问。

**Comment by chendelin1982** [comment]
refer to: https://github.com/Websoft9/StackHub/issues/46
