### ISSUE TITLE
website URL should fix[matomo]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#96]
**Describe the bug**

![image](https://user-images.githubusercontent.com/16741975/189825271-bfb1b84b-3dab-4c4b-b168-70ef799a2082.png)

same [issue](https://github.com/matomo-org/docker/issues/276) from other people

**Comment by qiaofeng1227** [comment]
configure nginx with domain and https:

![image](https://user-images.githubusercontent.com/43192516/190937033-2a3613e4-f9ea-47ba-ad22-c1f9e6b2d6bc.png)

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/190937224-1a263329-cea5-4b69-934b-b7edddd57906.png)

no warning
