### ISSUE TITLE
Update version to [v2.15.8] for [chatgptnextweb] ¥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#963]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by jinsheng200303** [comment]
### docker logs
~~~
docker logs chatgptnextweb_fgb0e
~~~
```
   ▲ Next.js 14.1.1
   - Local:        http://d43526cfed87:3000
   - Network:      http://172.18.0.9:3000

 ✓ Ready in 79ms
```
### screenshoot
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/d0d8af7e-24f7-47b6-80c6-0676f7e0a407">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/8e8164b2-6af7-4039-8266-3de30ee0ac2f">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/d1d24d2f-a463-4fea-9deb-930321085ac7">
