### ISSUE TITLE
Should skip database connection settings when at install wizard[matomo]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#97]
**What type of your feature request?**  

Should skip database connection settings when at install wizard

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/190936861-f298791a-f587-4e9c-8295-d1ad9dd4ca08.png)

click 【next】
![image](https://user-images.githubusercontent.com/43192516/190936910-a45e6d2f-a71b-48bc-8f33-ef57e668d0b7.png)
