### ISSUE TITLE
Update version to [2.1.5] for [flowise] ¥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#971]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by jinsheng200303** [comment]
### docker logs
~~~
docker logs flowise_dbzvp
~~~
```
2024-11-25 06:06:58 [INFO]: Starting Flowise...
2024-11-25 06:06:58 [INFO]: 📦 [server]: Data Source is initializing...
2024-11-25 06:07:02 [INFO]: 📦 [server]: Data Source has been initialized!
2024-11-25 06:07:02 [INFO]: ⚡️ [server]: Flowise Server is listening at :3000
2024-11-25 06:08:59 [INFO]: ⬆️ POST /api/v1/chatflows
```
### screenshoot
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/84808fec-8bfd-48b1-a4d0-e7b70b1b06d1">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e4acf6d0-cda4-457e-b106-44faabd08e63">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/203e7590-2659-4cd3-bd27-8c5bb83ec641">
