### ISSUE TITLE
Update version to [2.3.3] for [Penpot] ￥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#973]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by czj69233** [comment]
### docker logs penpot_9purk:
![image](https://github.com/user-attachments/assets/a083938a-09af-4aaa-b8bf-c63023b6b074)
### screenshoot:
![image](https://github.com/user-attachments/assets/ee0a6602-c934-4bbe-a5dd-c7c574033176)
![image](https://github.com/user-attachments/assets/765f96ff-0565-4e46-a3f8-25f5946ccd64)
![image](https://github.com/user-attachments/assets/0b662a69-3586-4837-9a1c-b022ac02cf1c)
