### ISSUE TITLE
Update version to 8.13.0 for pgadmin ￥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#974]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by czj69233** [comment]
### docker logs pgadmin_rhbsj:
```
postfix/postlog: starting the Postfix mail system
[2024-11-29 08:43:05 +0000] [1] [INFO] Starting gunicorn 22.0.0
[2024-11-29 08:43:05 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2024-11-29 08:43:05 +0000] [1] [INFO] Using worker: gthread
[2024-11-29 08:43:05 +0000] [88] [INFO] Booting worker with pid: 88
```
### screenshoot:
![image](https://github.com/user-attachments/assets/8fe5b00a-1b5d-4f5b-90d7-511ad6187322)
![image](https://github.com/user-attachments/assets/ca179df0-5427-468f-b9c1-42d223ac4da1)
![image](https://github.com/user-attachments/assets/5a83c1be-1367-43f8-a207-d943aa8ed0ed)
![image](https://github.com/user-attachments/assets/91a7d8b7-2798-43a5-8f3f-62ad8e67ce79)
