### ISSUE TITLE
Update version to 2.24.0 for portainer ￥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#975]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by czj69233** [comment]
### docker logs portainer_vv62c:
```
2024/11/29 08:28AM INF github.com/portainer/portainer/api/cmd/portainer/main.go:310 > encryption key file not present | filename=portainer
2024/11/29 08:28AM INF github.com/portainer/portainer/api/cmd/portainer/main.go:334 > proceeding without encryption key |
2024/11/29 08:28AM INF github.com/portainer/portainer/api/database/boltdb/db.go:124 > loading PortainerDB | filename=portainer.db
2024/11/29 08:28AM INF github.com/portainer/portainer/api/chisel/service.go:200 > found Chisel private key file on disk | private-key=/data/chisel/private-key.pem
2024/11/29 08:28:23 server: Reverse tunnelling enabled
2024/11/29 08:28:23 server: Fingerprint FkG8jhOAjtDzHL/VGv0ZmOy+Gz558AVrkqW2vMtuZoo=
2024/11/29 08:28:23 server: Listening on http://0.0.0.0:8000
2024/11/29 08:28AM INF github.com/portainer/portainer/api/cmd/portainer/main.go:601 > starting Portainer | build_number=128 go_version=go1.23.2 image_tag=2.24.0-linux-amd64 nodejs_version=18.20.4 version=2.24.0 webpack_version=5.88.2 yarn_version=1.22.22
2024/11/29 08:28AM INF github.com/portainer/portainer/api/http/server.go:365 > starting HTTPS server | bind_address=:9443
2024/11/29 08:28AM INF github.com/portainer/portainer/api/http/server.go:349 > starting HTTP server | bind_address=:9000
```
### screenshoot:
![image](https://github.com/user-attachments/assets/71a9b3de-9537-410e-8226-0bb9f4da909b)
![image](https://github.com/user-attachments/assets/abfc5944-cff0-4ad4-8ba5-468ee146eb6e)
![image](https://github.com/user-attachments/assets/0ddc02b6-4b53-4228-ad63-14f30d2fb854)
![image](https://github.com/user-attachments/assets/4be1dfca-35a3-4996-867f-6e1966c0aaec)
