### ISSUE TITLE
Update version to [0.57.1] for [trivy] ¥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#979]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by jinsheng200303** [comment]
### docker logs
~~~
docker logs trivy_lwoga
~~~
```
null
```

### screenshoot
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/ecb50453-9259-439b-8cdf-c2e80fe5b563">
<img width="1267" alt="image" src="https://github.com/user-attachments/assets/76f311ce-80e6-4837-9124-70e52a58a2c8">
