### ISSUE TITLE
Required a licensing key[mattermost]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#98]
**What type of your feature request?**  

- [ ] Add new features
- [x] Improve current features

Mattermost version is  5.36.1
![image](https://user-images.githubusercontent.com/62225175/141891123-f747337b-b67f-4b61-bd0b-f0c59b899f1e.png)

**Comment by chendelin1982** [comment]
refer to: https://github.com/Websoft9/ansible-mattermost/issues/8
