### ISSUE TITLE
Update version to [RELEASE.2024-11-07T00-52-20Z] for [minio] ￥10

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#987]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by qiuf12** [comment]
### docker logs
~~~
docker logs minio_qg89v
~~~
```
INFO: Formatting 1st pool, 1 set(s), 1 drives per set.
INFO: WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
MinIO Object Storage Server
Copyright: 2015-2024 MinIO, Inc.
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Version: RELEASE.2024-11-07T00-52-20Z (go1.23.3 linux/amd64)

API: http://minio.test2.websoft9.cn:7000 
WebUI: http://172.18.0.27:9001 http://127.0.0.1:9001  

Docs: https://docs.min.io
```
### screenshoot
<img width="957" alt="image" src="https://github.com/user-attachments/assets/752682e1-84b0-43a2-881b-d6caeea7c763">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/fcfecfa6-079d-48d7-bcd6-66e244aefa33">
