### ISSUE TITLE
can not change npm repository of  [nodejs runtime]?

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#989]
**What type of your feature request?**  

Can not change npm repository of  [nodejs runtime] by `npm set respository`?

**Do you have Clear solution**  

- [ ] No solution, need research
- [ ] Yes, solution detail below

Discribe you solution here:  

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by zhaojing1987** [comment]
node容器默认为production模式  
查看命令：echo $NODE_ENV
通过  NODE_ENV=development 或 production    可以切换
生产模式下是不会安装dev的依赖包的，如果是进行开发调试，会导致依赖报错；
用户需要根据自己实际的需求进行设置  （这里还是要向用户说明）

node切换源：
默认为官方源：http://registry.npmjs.org/
查看命令：npm config get registry
切换命令：npm config set registry https://registry.npm.taobao.org/  (淘宝源)
